### ISSUE TITLE
Question about maintenance

### ISSUE THREAD

**Issue by tobias47n9e** [EasyScreenCast/EasyScreenCast#109]
The README says that the project is no longer maintained. Is there still someone that will accept patches and updates the version at extensions.gnome.org?

**Comment by iacopodeenosee** [comment]
no longer interested in the project, I believe the best solution is for someone to adopt it, fork it and create a new project of extensions.gnome.org, i can redirect the user to the new project links. thx

**Comment by tobias47n9e** [comment]
Could you move the repo to an organization and add me as a maintainer? The organization name "EasyScreenCast" is available and then the repo would be easy to find and would keep the issues and history.

https://github.com/organizations/new

**Comment by iacopodeenosee** [comment]
done. will you open a new project page on extensions.gnome.org? or you want use the old one?

**Comment by tobias47n9e** [comment]
If it is possible to use the old one that would be great. Is there a way to have more than one maintainer on extensions.gnome.org?

Can you give me admin rights on Github. I promise to be careful with accepting merge requests.

**Comment by iacopodeenosee** [comment]
> Is there a way to have more than one maintainer on extensions.gnome.org?

no it's not possible, if you want i can upload the new release you create, in that page i update the info to the new repo you need to update the repo url into the window preference too.

> Can you give me admin rights on Github

done

**Comment by tobias47n9e** [comment]
Thanks! I will make some updates later today and then tag the new version. Should we move the wordpress page to a github page, so everything is in one place?

**Comment by iacopodeenosee** [comment]
already done :+1: , If you need help there is someone else willing to help in the project, you find the account name in the last pull request, however, it's your choice :)

**Comment by tobias47n9e** [comment]
Thanks. I can use all the help I can get :) I don't know too much about shell extensions. But I also hope to learn more about them soon, so I can be of more help.
