### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by OsarNick** [EasyScreenCast/EasyScreenCast#112]
How this video look in Windows?

**Comment by tobias47n9e** [comment]
@OsarNick Not sure I understand the question. Can you explain it in a few sentences?

EasyScreenCast is a Gnome shell-extension. So it is probably not the best tool for screen recording on Windows.

You can also post a question here if you want software advice: http://softwarerecs.stackexchange.com/

**Comment by OsarNick** [comment]
Sorry, a I'm from Russhia, and my englich its bad. Recorded video open in
linux. In windows recorded video not open. Its normal?
01.11.2016 22:43 пользователь "Tobias Schönberg" <notifications@github.com>
написал:

**Comment by tobias47n9e** [comment]
Did you try with VLC player on Windows? It might be an issue with missing codecs. You could also try converting the video to a different format. Let me know if that worked for you.

**Comment by OsarNick** [comment]
This video not open in Sony Vegas Pro. Mauby problem with codec in Sony
Vegas?

2016-11-01 23:05 GMT+03:00 Tobias Schönberg <notifications@github.com>:

**Comment by deriherdianto** [comment]
![screen](https://cloud.githubusercontent.com/assets/8337409/19936150/25f4e482-a14f-11e6-847c-1461e5ac29c4.png)

**Comment by OsarNick** [comment]
Thank you!


2016-11-02 17:53 GMT+02:00 Deri Herdianto <notifications@github.com>:

**Comment by tobias47n9e** [comment]
You're welcome!
