### ISSUE TITLE
Audio Recording problem

### ISSUE THREAD

**Issue by exayyan** [EasyScreenCast/EasyScreenCast#121]
Unable to record audio, or unable to use mic direct with speaker like headset (if i want to do, i must record video and speak something then i can hear ) also unable to record audio in kali linux 2.2. Fix it please.

**Comment by tobias47n9e** [comment]
@exayyan I will need more information in order to fix this.

Can you record audio normally with another program?
Did you look at the logs for the extension?
What kind of settings did you use to record?

**Comment by pattersonrptr** [comment]
The problem can be the volume of the microphone, it's at zero for default on Kali, just increase the volume.

**Comment by tobias47n9e** [comment]
@pattersonrptr Thank you for the suggestion. @exayyan It is always good to do audio checks with e.g. Audacity before, to see if all the audio settings are correct.

**Comment by iacopodeenosee** [comment]
I think this can be closed, if anyone has an audio problem then can create a new issue again
