### ISSUE TITLE
Feature request: .GIF output

### ISSUE THREAD

**Issue by cortopy** [EasyScreenCast/EasyScreenCast#122]
This is just a feature request not a bug to ask whether .GIF output is possible.

I was reading the docs for [gnome-shell](https://wiki.gnome.org/Projects/GnomeShell/CheatSheet#Screencast_recording) and I can see the default output is WebM. At first I thought it would appropriate to ask for this feature to gnome-shell project direct. However, I'm assuming that the great EasyScreenCast is what is really offering extra output configs. 

Would it be possible to add .GIF too?

**Comment by tobias47n9e** [comment]
I will investigate.

**Comment by iacopodeenosee** [comment]
sorry but **gstreamer can NOT create a animated gif**, It can only create static gif, just pictures.
The only solution that i found is to create a script to be launched once the recording is finished that convert the movie into gif, you just have to add on **Command post-recording** option this command:
`ffmpeg -i _fpath -pix_fmt rgb24 _dirpath/_fname.gif`
_Is to optimize the command to find a compromise between size and quality_
@tobias47n9e can we create in the README a section explaining how to automatically convert the screencast to gif?
