### ISSUE TITLE
Countdown feature request

### ISSUE THREAD

**Issue by jenschurchill** [EasyScreenCast/EasyScreenCast#125]
Would it be possible, for the countdown to be displayed on the topbar icon?

**Comment by tobias47n9e** [comment]
@jenschurchill I assume you talking about the recording time? The code to show it, is already merged, but not released yet. Hopefully I can fix the other blocking issues during the holidays.

Relevant merge:
 * https://github.com/EasyScreenCast/EasyScreenCast/pull/117

**Comment by iacopodeenosee** [comment]
@tobias47n9e I think it can be close, you have already implemented it.

**Comment by tobias47n9e** [comment]
@iacopodeenosee Thanks. This is released now so I think we can close.
