### ISSUE TITLE
Feature request: Trim last x seconds...

### ISSUE THREAD

**Issue by jenschurchill** [EasyScreenCast/EasyScreenCast#126]
Would it be possible to set a auto trim of the x last seconds.
Opening a video editor, to remove the last 2 seconds of clicking "EasyScreenCast Icon, Stop recording" when forgetting to use the hotkey requires work, which goes against users being lazy ;)

**Comment by tobias47n9e** [comment]
@jenschurchill I am not even sure if that is possible. Will need some investigating.

**Comment by iacopodeenosee** [comment]
As predicted @tobias47n9e is not possible auto trim of the last seconds, **remember that it is always possible to enable/disable recording right-click on the extension icon**, Just not to have

> the last 2 seconds of clicking "EasyScreenCast Icon, Stop recording"
