### ISSUE TITLE
Argument 'accelerator' but got type 'undefined' when loading the preferences dialog

### ISSUE THREAD

**Issue by XasanMarabu** [EasyScreenCast/EasyScreenCast#130]
I've got an error when try to get Options

`Error: Expected type utf8 for Argument 'accelerator' but got type 'undefined'

Stack trace:
  EasyScreenCastSettingsWidget<._updateRowShortcut@/home/xasan/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/prefs.js:569
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178
  EasyScreenCastSettingsWidget<._init@/home/xasan/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/prefs.js:526
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178
  buildPrefsWidget@/home/xasan/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/prefs.js:753
  Application<._selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:90
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178
  Application<._onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:238
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178
  main@resource:///org/gnome/shell/extensionPrefs/main.js:376
  @<main>:1`
![screenshot-20170302215459](https://cloud.githubusercontent.com/assets/26581796/24168561/4c7bb620-0e83-11e7-9da4-e38d4888d621.png)

Also I've got "ERROR  RECORDER See logs for more info" when trying to record

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Logs

 * Log, **enable verbose debug logs** into options window, and after that try  

$ journalctl --since=today --no-pager | grep js
Mar 21 21:49:26 dell org.gnome.Shell.desktop[2950]:   inflating: /home/xasan/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/selection.js
Mar 21 21:49:26 dell org.gnome.Shell.desktop[2950]:   inflating: /home/xasan/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/convenience.js
Mar 21 21:49:26 dell org.gnome.Shell.desktop[2950]:   inflating: /home/xasan/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/extension.js
Mar 21 21:49:26 dell org.gnome.Shell.desktop[2950]:   inflating: /home/xasan/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/timer.js
Mar 21 21:49:26 dell org.gnome.Shell.desktop[2950]:   inflating: /home/xasan/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/utilgsp.js
Mar 21 21:49:26 dell org.gnome.Shell.desktop[2950]:   inflating: /home/xasan/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/prefs.js
Mar 21 21:49:26 dell org.gnome.Shell.desktop[2950]:   inflating: /home/xasan/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/gulpfile.js
Mar 21 21:49:26 dell org.gnome.Shell.desktop[2950]:   inflating: /home/xasan/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/utilnotify.js
Mar 21 21:49:26 dell org.gnome.Shell.desktop[2950]:   inflating: /home/xasan/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/utilaudio.js
Mar 21 21:49:26 dell org.gnome.Shell.desktop[2950]:   inflating: /home/xasan/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/package.json
Mar 21 21:49:26 dell org.gnome.Shell.desktop[2950]:   inflating: /home/xasan/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/utilwebcam.js
Mar 21 21:49:26 dell org.gnome.Shell.desktop[2950]:   inflating: /home/xasan/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/utilrecorder.js
Mar 21 21:49:26 dell org.gnome.Shell.desktop[2950]:  extracting: /home/xasan/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/metadata.json
                                        _disconnect@resource:///org/gnome/gjs/modules/signals.js:74
                                        PopupMenuBase<._connectItemSignals/menuItem._popupMenuDestroyId<@resource:///org/gnome/shell/ui/popupMenu.js:562
                                        _emit@resource:///org/gnome/gjs/modules/signals.js:124
                                        PopupBaseMenuItem<._onDestroy@resource:///org/gnome/shell/ui/popupMenu.js:214
                                        wrapper@resource:///org/gnome/gjs/modules/lang.js:178
                                        PopupBaseMenuItem<.destroy@resource:///org/gnome/shell/ui/popupMenu.js:210
                                        wrapper@resource:///org/gnome/gjs/modules/lang.js:178
                                        _parent@resource:///org/gnome/gjs/modules/lang.js:131
                                        PopupSubMenuMenuItem<.destroy@resource:///org/gnome/shell/ui/popupMenu.js:1106
                                        wrapper@resource:///org/gnome/gjs/modules/lang.js:178
                                        PopupMenuBase<.removeAll@resource:///org/gnome/shell/ui/popupMenu.js:707
                                        wrapper@resource:///org/gnome/gjs/modules/lang.js:178
                                        PopupMenuBase<.destroy@resource:///org/gnome/shell/ui/popupMenu.js:720
                                        wrapper@resource:///org/gnome/gjs/modules/lang.js:178
                                        _parent@resource:///org/gnome/gjs/modules/lang.js:131
                                        PopupMenu<.destroy@resource:///org/gnome/shell/ui/popupMenu.js:848
                                        wrapper@resource:///org/gnome/gjs/modules/lang.js:178
                                        Button<.destroy@resource:///org/gnome/shell/ui/panelMenu.js:185
                                        wrapper@resource:///org/gnome/gjs/modules/lang.js:178
                                        _parent@resource:///org/gnome/gjs/modules/lang.js:131
                                        EasyScreenCast_Indicator<.destroy@/home/xasan/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/extension.j :651
                                        wrapper@resource:///org/gnome/gjs/modules/lang.js:178
                                        disable@/home/xasan/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/extension.js:704
                                        disableExtension@resource:///org/gnome/shell/ui/extensionSystem.js:81
                                        onEnabledExtensionsChanged/<@resource:///org/gnome/shell/ui/extensionSystem.js:267
                                        onEnabledExtensionsChanged@resource:///org/gnome/shell/ui/extensionSystem.js:266
                                        _disconnect@resource:///org/gnome/gjs/modules/signals.js:74
                                        PopupMenuBase<._connectItemSignals/menuItem._popupMenuDestroyId<@resource:///org/gnome/shell/ui/popupMenu.js:562
                                        _emit@resource:///org/gnome/gjs/modules/signals.js:124
                                        PopupBaseMenuItem<._onDestroy@resource:///org/gnome/shell/ui/popupMenu.js:214
                                        wrapper@resource:///org/gnome/gjs/modules/lang.js:178
                                        PopupBaseMenuItem<.destroy@resource:///org/gnome/shell/ui/popupMenu.js:210
                                        wrapper@resource:///org/gnome/gjs/modules/lang.js:178
                                        _parent@resource:///org/gnome/gjs/modules/lang.js:131
                                        PopupSubMenuMenuItem<.destroy@resource:///org/gnome/shell/ui/popupMenu.js:1106
                                        wrapper@resource:///org/gnome/gjs/modules/lang.js:178
                                        PopupMenuBase<.removeAll@resource:///org/gnome/shell/ui/popupMenu.js:707
                                        wrapper@resource:///org/gnome/gjs/modules/lang.js:178
                                        PopupMenuBase<.destroy@resource:///org/gnome/shell/ui/popupMenu.js:720
                                        wrapper@resource:///org/gnome/gjs/modules/lang.js:178
                                        _parent@resource:///org/gnome/gjs/modules/lang.js:131
                                        PopupMenu<.destroy@resource:///org/gnome/shell/ui/popupMenu.js:848
                                        wrapper@resource:///org/gnome/gjs/modules/lang.js:178
                                        Button<.destroy@resource:///org/gnome/shell/ui/panelMenu.js:185
                                        wrapper@resource:///org/gnome/gjs/modules/lang.js:178
                                        _parent@resource:///org/gnome/gjs/modules/lang.js:131
                                        EasyScreenCast_Indicator<.destroy@/home/xasan/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/extension.j :651
                                        wrapper@resource:///org/gnome/gjs/modules/lang.js:178
                                        disable@/home/xasan/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/extension.js:704
                                        disableExtension@resource:///org/gnome/shell/ui/extensionSystem.js:81
                                        onEnabledExtensionsChanged/<@resource:///org/gnome/shell/ui/extensionSystem.js:267
                                        onEnabledExtensionsChanged@resource:///org/gnome/shell/ui/extensionSystem.js:266

## Your Environment

* where you downloaded the extension?
 [ ] Gnome shell extension website

* gnome shell version:

$ gnome-shell --version
GNOME Shell 3.20.4

* Operating System and version:

$ lsb_release -a && uname -a
Distributor ID:	Ubuntu
Description:	Ubuntu 16.10
Release:	16.10
Codename:	yakkety
Linux dell 4.8.0-41-generic #44-Ubuntu SMP Fri Mar 3 15:27:17 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by tobias47n9e** [comment]
Sorry about the issue. Will hopefully have time soon to look into some of these issues.

**Comment by iacopodeenosee** [comment]
i think there is a not valid value for gtk accelerator stored into gschema file, for fixing this you need to remove this file and recompile the new one.
```
rm ~/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/schemas/gschemas.compiled

glib-compile-schemas ~/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/schemas/org.gnome.shell.extensions.easyscreencast.gschema.xml
```
@tobias47n9e 
maybe we can add a function that checks that the entered value is valid...

**Comment by krasi-georgiev** [comment]
just installed on fedora 27 and clicking the setting button in the try always displays

Error: Expected type utf8 for Argument 'accelerator' but got type 'undefined'

Stack trace:
  EasyScreenCastSettingsWidget<._updateRowShortcut@/home/krasi/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/prefs.js:528:28
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  EasyScreenCastSettingsWidget<._init@/home/krasi/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/prefs.js:484:13
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  buildPrefsWidget@/home/krasi/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/prefs.js:633:18
  Application<._selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:91:22
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  Application<._onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:246:17
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  main@resource:///org/gnome/shell/extensionPrefs/main.js:402:5
  @<main>:1:43

**Comment by adangel** [comment]
So this error "`Error: Expected type utf8 for Argument 'accelerator' but got type 'undefined'" is displayed, when `Gtk.accelerator_parse(undefined)` is called (https://gjs-docs.gnome.org/gtk40~4.2.1/gtk.accelerator_parse).

This happens, if the accelerator has been removed and no accelerator is stored in the settings anymore.
