### ISSUE TITLE
Asynchron audio when changing the volume during the recording

### ISSUE THREAD

**Issue by CrimsonFork** [EasyScreenCast/EasyScreenCast#137]
## Expected Behavior
Audio keeps synchron even if the volume gets changed

## Current Behavior
Audio doesn't keep synchron if the volume gets changed

## Steps to Reproduce
https://youtu.be/c-ne7pfveuc (May not be available just yet since YouTube seems to have problems with webm)
1. Start the recording
2. Record sound
3. Change volume
4. Continue recording

## Your Environment
* Where did you download the extension?
 [x] Gnome shell extension website
 [ ] From Git (Add commit tag)
* Gnome shell version:
GNOME Shell 3.14.4
* Operating System and version:
Debian GNU/Linux 8 (jessie) 64-Bit
* Wayland or X?
X

**Comment by iacopodeenosee** [comment]
I did some tests and I can not reproduce the error, can you make a recording directly from the terminal? I think it's a problem with the integrated gnome-shell recorder; after execute this **[1]** can you see in the logs some alerts or latency errors?
**[1]** 
```
gst-launch-1.0  --gst-debug=3 \
ximagesrc \
! queue max-size-buffers=0 max-size-time=0 max-size-bytes=0  \
! videoconvert \
! vp8enc min_quantizer=4 max_quantizer=13 cpu-used=2 deadline=500000 sharpness=0 target-bitrate=15000 threads=2  \
! queue max-size-buffers=0 max-size-time=0 max-size-bytes=0  \
! mux. pulsesrc  \
! audioconvert  \
! vorbisenc  \
! queue max-size-buffers=0 max-size-time=0 max-size-bytes=0  \
! mux. webmmux name=mux \
! filesink location=screencast.webm
```
in this command record the default pulse audio source and and mix it into a webm file with vp8 codec, if you need fit these parameters to your situation. thx

**Comment by OffifialMITX** [comment]
Sorry for the delay, I've upgraded to Debian 9 recently and now the only game I had doesn't want to work, but I'm looking for something else to reproduce it with.

**Comment by OffifialMITX** [comment]
Alright, I've managed to fix it and the bug still persists.

**Comment by OffifialMITX** [comment]
Erm... How do I do this?

**Comment by iacopodeenosee** [comment]
> Erm... How do I do this?

execute this into a terminal: 
```
gst-launch-1.0  --gst-debug=3 \
ximagesrc \
! queue max-size-buffers=0 max-size-time=0 max-size-bytes=0  \
! videoconvert \
! vp8enc min_quantizer=4 max_quantizer=13 cpu-used=2 deadline=500000 sharpness=0 target-bitrate=15000 threads=2  \
! queue max-size-buffers=0 max-size-time=0 max-size-bytes=0  \
! mux. pulsesrc  \
! audioconvert  \
! vorbisenc  \
! queue max-size-buffers=0 max-size-time=0 max-size-bytes=0  \
! mux. webmmux name=mux \
! filesink location=screencast.webm
```
recreates the situation where you have noticed asynchrony, if in the terminal, where you ran the command above, you notice latency errors than send us these log, however 

> I think it's a problem with the integrated gnome-shell recorder

and you should ask for support in the gstreamer channels

**Comment by OffifialMITX** [comment]
Well somethihg's wrong, because when I try to execute it I only get an error message that gst-launch-1.0 is not found. I'm not at my PC at the moment so the original error message will be providen later.

PS: That's actually why I wasn't sure how I do this.

**Comment by iacopodeenosee** [comment]
@OffifialMITX have you got [these](https://github.com/EasyScreenCast/EasyScreenCast#requirements)?

**Comment by OffifialMITX** [comment]
Yes, I do. And I the only thing I can find via apt search is rygel-gst-launch. Should I try installing it?

**Comment by OffifialMITX** [comment]
Here is a [video example](https://drive.google.com/open?id=0B8HcTODSY2XzOHVPenJaZUNkRFU).

**Comment by iacopodeenosee** [comment]
> Should I try installing it?

i can't help you on that, try to get support for your distros community.
