### ISSUE TITLE
FR Extend the UI/fuctionality

### ISSUE THREAD

**Issue by OffifialMITX** [EasyScreenCast/EasyScreenCast#138]
I'd like to have two things:

1. A small window with a preview of the area, a sfx indicator and buttons to start/pause/stop the recording.

2. A minimal video editor with multiple timelines, simple fade functions, cutting/extending tool and a control of the filter used for up/downscaling.

Would you be able to realize this? I'd be happy to provide icons if needed.

**Comment by iacopodeenosee** [comment]
> 1. A small window with a preview of the area, a sfx indicator and buttons to start/pause/stop the recording.

what do you mean with a small preview? like the video of the concurrent screencast in a corner of the screen? what's a sfx indicator? there is no problem to create the buttons to start and stop, but the pause button can not be done

> 2. A minimal video editor with multiple timelines, simple fade functions, cutting/extending tool and a control of the filter used for up/downscaling.

this "minimal video editor" takes a lot of time, which I unfortunately not have, I can barely find the time to handle the existing code, I think there are many programs that make video editing better than they can with a GNOME shell extension, why not use those? however you can be able to open the screencast movie from your video editing software through the extension as soon as you've finished recording. thx

**Comment by OffifialMITX** [comment]
I mean a small window which also exists during the recording and contains an element which is a mirror of the recorded screen area, like gtkrecordmydesktop does but only the selected area and not the whole screen. SFX is for sound effects or sound in general. The indicator I've described is a visual feedback of the input audio mainly for the purpose of seeing if the audio is too loud rather tham make a test recording, listen to it and only then knowing if everything works out the way you want.

Y is a pause button not possible?

**Comment by iacopodeenosee** [comment]
> I mean a small window which also exists during the recording and contains an element which is a mirror of the recorded screen area, like gtkrecordmydesktop does but only the selected area and not the whole screen.

https://github.com/EasyScreenCast/EasyScreenCast/issues/143

> The indicator I've described is a visual feedback of the input audio mainly for the purpose of seeing if the audio is too loud rather tham make a test recording, listen to it and only then knowing if everything works out the way you want.

**This is interesting** and we can implement it in the new audio selection tab. In addition to the ability to mix different audio streams we could test audio levels, [best to continue here](https://github.com/EasyScreenCast/EasyScreenCast/issues/92)

> Y is a pause button not possible?

the gnomse shell integtred recorder not expose the possibility of pausing recording, we could create a workaround via code but as a solution I do not like, _too dirty_. Howerver you can comment this at https://github.com/EasyScreenCast/EasyScreenCast/issues/90
