### ISSUE TITLE
webcam 

### ISSUE THREAD

**Issue by delta12kilo** [EasyScreenCast/EasyScreenCast#139]
webcam isn't recording. I've selected the integrated_webcam_HD but it still only recording the screen no webcam...!! help!!

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Logs

 * Use `journalctl /usr/bin/gnome-shell -f` to monitor Gnome shell activity. Maybe the crash will log something.
 * Log, **enable verbose debug logs** into options window, and after that try  
 `journalctl --since=today --no-pager | grep js`
 * webcam info:
 `v4l2-ctl --all`
 * webcam info:
 `for VIDEO_DEVICE in /dev/video* ; do echo ; echo ; echo $VIDEO_DEVICE ; echo ; v4l2-ctl --device=$VIDEO_DEVICE --list-inputs ; done`
 * webcam info:
 `GST_DEBUG=v4l2src:5 gst-launch-1.0 v4l2src num-buffers=1 ! fakesink | grep probed`

## Your Environment

* Where did you download the extension?
 [ ] Gnome shell extension website
 [ ] From Git (Add commit tag)
* Gnome shell version:

* Operating System and version:

* Wayland or X?

**Comment by iacopodeenosee** [comment]
hi, we need **MORE** info to resolve this kind of problems;
please read [this](https://github.com/EasyScreenCast/EasyScreenCast/blob/master/.github/ISSUE_TEMPLATE.md#logs) and paste here the logs. thx
