### ISSUE TITLE
Unable to record when an audio source is slected

### ISSUE THREAD

**Issue by brittadams** [EasyScreenCast/EasyScreenCast#146]
Unable to record when any audio source is selected
## Steps to Reproduce (for bugs)

1.Choose audio source and start recording
2.
3.
4.

## Logs
root@kali:~# journalctl --since 23:41 --no-pager | grep JS
Jul 04 23:41:18 kali gnome-shell[1331]: JS LOG: [ESC]-*-refresh indicator -A false -F false
Jul 04 23:41:18 kali gnome-shell[1331]: JS LOG: [ESC]-*-refresh indicator -A false -F true
Jul 04 23:41:20 kali gnome-shell[1331]: JS LOG: [ESC]-*-left click indicator
Jul 04 23:41:20 kali gnome-shell[1331]: JS LOG: [ESC]-*-reset the sub menu audio
Jul 04 23:41:20 kali gnome-shell[1331]: JS LOG: [ESC]-*-add new items to sub menu audio
Jul 04 23:41:20 kali gnome-shell[1331]: JS LOG: [ESC]-#-get list input audio
Jul 04 23:41:20 kali gnome-shell[1331]: JS LOG: [ESC]-#-Mixer sink -> 1
Jul 04 23:41:20 kali gnome-shell[1331]: JS LOG: [ESC]-#-sink index: 0
Jul 04 23:41:20 kali gnome-shell[1331]: JS LOG: [ESC]-#-sink name: alsa_output.pci-0000_00_1f.3.analog-stereo
Jul 04 23:41:20 kali gnome-shell[1331]: JS LOG: [ESC]-#-sink description: Built-in Audio Analog Stereo
Jul 04 23:41:20 kali gnome-shell[1331]: JS LOG: [ESC]-#-sink port: analog-output-speaker
Jul 04 23:41:20 kali gnome-shell[1331]: JS LOG: [ESC]-#-Mixer sources -> 2
Jul 04 23:41:20 kali gnome-shell[1331]: JS LOG: [ESC]-#-source index: 1
Jul 04 23:41:20 kali gnome-shell[1331]: JS LOG: [ESC]-#-source name: alsa_input.pci-0000_00_1f.3.analog-stereo
Jul 04 23:41:20 kali gnome-shell[1331]: JS LOG: [ESC]-#-source description: Built-in Audio Analog Stereo
Jul 04 23:41:20 kali gnome-shell[1331]: JS LOG: [ESC]-#-source port: analog-input-mic
Jul 04 23:41:20 kali gnome-shell[1331]: JS LOG: [ESC]-#-source index: 2
Jul 04 23:41:20 kali gnome-shell[1331]: JS LOG: [ESC]-#-source name: alsa_input.usb-0c76_USB_PnP_Audio_Device-00.analog-mono
Jul 04 23:41:20 kali gnome-shell[1331]: JS LOG: [ESC]-#-source description: USB PnP Audio Device Analog Mono
Jul 04 23:41:20 kali gnome-shell[1331]: JS LOG: [ESC]-#-source port: analog-input-mic
Jul 04 23:41:20 kali gnome-shell[1331]: JS LOG: [ESC]-#-MIXER SOURCE TOT -> 3
Jul 04 23:41:20 kali gnome-shell[1331]: JS LOG: [ESC]-*-get audio choice from pref 4
Jul 04 23:41:20 kali gnome-shell[1331]: JS LOG: [ESC]-*-refresh indicator -A false -F false
Jul 04 23:41:22 kali gnome-shell[1331]: JS LOG: [ESC]-*-start recording
Jul 04 23:41:22 kali gnome-shell[1331]: JS LOG: [ESC]-*-recording full area
Jul 04 23:41:22 kali gnome-shell[1331]: JS LOG: [ESC]-*-instant recording called
Jul 04 23:41:22 kali gnome-shell[1331]: JS LOG: [ESC]-&-start video recording
Jul 04 23:41:22 kali gnome-shell[1331]: JS LOG: [ESC]-§-get file extension C-> 0
Jul 04 23:41:22 kali gnome-shell[1331]: JS LOG: [ESC]-§-COMPOSE GSP
Jul 04 23:41:22 kali gnome-shell[1331]: JS LOG: [ESC]-#-mixer _init
Jul 04 23:41:22 kali gnome-shell[1331]: JS LOG: [ESC]-#-mixer exist -> [object instance proxy GIName:Gvc.MixerControl jsobj@0x7fd91bc89580 native@0x55e58ebb9db0] state -> 1
Jul 04 23:41:22 kali gnome-shell[1331]: JS LOG: [ESC]-§-get option||devW: 0||devA: 4||Qgsp: 1||Qwc: ||Res: 0||Cont: 0
Jul 04 23:41:22 kali gnome-shell[1331]: JS LOG: [ESC]-§-SCREEN-AUDIO
Jul 04 23:41:22 kali gnome-shell[1331]: JS LOG: [ESC]-§-replace audio default->false
Jul 04 23:41:22 kali gnome-shell[1331]: JS LOG: [ESC]-§-pipeline pre-audio:queue max-size-buffers=0 max-size-time=0 max-size-bytes=0 ! _SCREENCAST_RES_ _ENCODER_VIDEO_ ! queue max-size-buffers=0 max-size-time=0 max-size-bytes=0 ! mux. pulsesrc ! audioconvert ! _ENCODER_AUDIO_ ! queue max-size-buffers=0 max-size-time=0 max-size-bytes=0 ! mux. _CONTAINER_ name=mux  aq:vorbisenc
Jul 04 23:41:22 kali gnome-shell[1331]: JS LOG: [ESC]-#-get source audio choosen
Jul 04 23:41:22 kali gnome-shell[1331]: JS LOG: [ESC]-#-get list input audio
Jul 04 23:41:22 kali gnome-shell[1331]: JS LOG: [ESC]-#-Mixer sink -> 1
Jul 04 23:41:22 kali gnome-shell[1331]: JS LOG: [ESC]-#-sink index: 0
Jul 04 23:41:22 kali gnome-shell[1331]: JS LOG: [ESC]-#-sink name: alsa_output.pci-0000_00_1f.3.analog-stereo
Jul 04 23:41:22 kali gnome-shell[1331]: JS LOG: [ESC]-#-sink description: Built-in Audio Analog Stereo
Jul 04 23:41:22 kali gnome-shell[1331]: JS LOG: [ESC]-#-sink port: analog-output-speaker
Jul 04 23:41:22 kali gnome-shell[1331]: JS LOG: [ESC]-#-Mixer sources -> 2
Jul 04 23:41:22 kali gnome-shell[1331]: JS LOG: [ESC]-#-source index: 1
Jul 04 23:41:22 kali gnome-shell[1331]: JS LOG: [ESC]-#-source name: alsa_input.pci-0000_00_1f.3.analog-stereo
Jul 04 23:41:22 kali gnome-shell[1331]: JS LOG: [ESC]-#-source description: Built-in Audio Analog Stereo
Jul 04 23:41:22 kali gnome-shell[1331]: JS LOG: [ESC]-#-source port: analog-input-mic
Jul 04 23:41:22 kali gnome-shell[1331]: JS LOG: [ESC]-#-source index: 2
Jul 04 23:41:22 kali gnome-shell[1331]: JS LOG: [ESC]-#-source name: alsa_input.usb-0c76_USB_PnP_Audio_Device-00.analog-mono
Jul 04 23:41:22 kali gnome-shell[1331]: JS LOG: [ESC]-#-source description: USB PnP Audio Device Analog Mono
Jul 04 23:41:22 kali gnome-shell[1331]: JS LOG: [ESC]-#-source port: analog-input-mic
Jul 04 23:41:22 kali gnome-shell[1331]: JS LOG: [ESC]-#-MIXER SOURCE TOT -> 3
Jul 04 23:41:22 kali gnome-shell[1331]: JS LOG: [ESC]-§-correct audio source assignment
Jul 04 23:41:22 kali gnome-shell[1331]: JS LOG: [ESC]-§-pipeline post-audio:queue max-size-buffers=0 max-size-time=0 max-size-bytes=0 ! _SCREENCAST_RES_ _ENCODER_VIDEO_ ! queue max-size-buffers=0 max-size-time=0 max-size-bytes=0 ! mux. pulsesrc device="alsa_input.usb-0c76_USB_PnP_Audio_Device-00.analog-mono" ! audioconvert ! vorbisenc ! queue max-size-buffers=0 max-size-time=0 max-size-bytes=0 ! mux. _CONTAINER_ name=mux 
Jul 04 23:41:22 kali gnome-shell[1331]: JS LOG: [ESC]-§-final GSP :queue max-size-buffers=0 max-size-time=0 max-size-bytes=0 !  vp8enc min_quantizer=4 max_quantizer=13 cpu-used=2 deadline=500000 sharpness=0 target-bitrate=15000 threads=%T ! queue max-size-buffers=0 max-size-time=0 max-size-bytes=0 ! mux. pulsesrc device="alsa_input.usb-0c76_USB_PnP_Audio_Device-00.analog-mono" ! audioconvert ! vorbisenc ! queue max-size-buffers=0 max-size-time=0 max-size-bytes=0 ! mux. webmmux name=mux 
Jul 04 23:41:22 kali gnome-shell[1331]: JS LOG: [ESC]-&-path/file template : Screencast_%d_%t.webm
Jul 04 23:41:22 kali gnome-shell[1331]: JS LOG: [ESC]-*-refresh indicator -A false -F undefined
Jul 04 23:41:22 kali gnome-shell[1331]: JS LOG: [ESC]-&-screencast execute - false - 
Jul 04 23:41:22 kali gnome-shell[1331]: JS LOG: [ESC]-*-record ERROR
Jul 04 23:41:22 kali gnome-shell[1331]: JS LOG: [ESC]-*-show error notify
Jul 04 23:41:22 kali gnome-shell[1331]: JS LOG: [ESC]-°-create notify :ERROR RECORDER - See logs for more info
Jul 04 23:41:22 kali gnome-shell[1331]: JS LOG: Trying to re-add source System Information
Jul 04 23:41:22 kali gnome-shell[1331]: JS LOG: [ESC]-*-refresh indicator -A false -F undefined
Jul 04 23:46:03 kali gnome-shell[1331]: JS LOG: [ESC]-*-refresh indicator -A false -F true
Jul 04 23:46:03 kali gnome-shell[1331]: JS LOG: [ESC]-*-refresh indicator -A false -F false
Jul 04 23:47:37 kali gnome-shell[1331]: JS LOG: [ESC]-#-mixer stream add - ID: 46
Jul 04 23:47:37 kali gnome-shell[1331]: JS LOG: [ESC]-#-mixer stream add - ID: 46
Jul 04 23:47:37 kali gnome-shell[1331]: JS LOG: [ESC]-#-mixer stream add - ID: 46
Jul 04 23:47:37 kali gnome-shell[1331]: JS LOG: [ESC]-#-mixer stream add - ID: 46
Jul 04 23:47:37 kali gnome-shell[1331]: JS LOG: [ESC]-#-mixer stream add - ID: 46
Jul 04 23:47:37 kali gnome-shell[1331]: JS LOG: [ESC]-#-mixer stream add - ID: 46
Jul 04 23:47:37 kali gnome-shell[1331]: JS LOG: [ESC]-#-mixer stream add - ID: 46
Jul 04 23:47:37 kali gnome-shell[1331]: JS LOG: [ESC]-#-mixer stream remove - ID: 46
Jul 04 23:47:37 kali gnome-shell[1331]: JS LOG: [ESC]-#-mixer stream remove - ID: 46
Jul 04 23:47:37 kali gnome-shell[1331]: JS LOG: [ESC]-#-mixer stream remove - ID: 46
Jul 04 23:47:37 kali gnome-shell[1331]: JS LOG: [ESC]-#-mixer stream remove - ID: 46
Jul 04 23:47:37 kali gnome-shell[1331]: JS LOG: [ESC]-#-mixer stream remove - ID: 46
Jul 04 23:47:37 kali gnome-shell[1331]: JS LOG: [ESC]-#-mixer stream remove - ID: 46
Jul 04 23:47:37 kali gnome-shell[1331]: JS LOG: [ESC]-#-mixer stream remove - ID: 46
Jul 04 23:47:39 kali gnome-shell[1331]: JS LOG: [ESC]-*-refresh indicator -A false -F true
Jul 04 23:47:39 kali gnome-shell[1331]: JS LOG: [ESC]-*-refresh indicator -A false -F false
Jul 04 23:47:39 kali gnome-shell[1331]: JS LOG: [ESC]-*-refresh indicator -A false -F false

## Your Environment

* Where did you download the extension?
Preinstalled with Kali Linux
 [ ] Gnome shell extension website
 [ ] From Git (Add commit tag)
* Gnome shell version:
3.22.3
* Operating System and version:
Kali Linux
* Wayland or X?
X11

**Comment by iacopodeenosee** [comment]
The GSP looks good, you probably miss the gst-plugin for vp8 encoding, however you can try launching this command **[1]** into a terminal, in the output will get more information.
**[1]**
```
gst-launch-1.0  --gst-debug=3 \
ximagesrc \
! queue max-size-buffers=0 max-size-time=0 max-size-bytes=0  \
! videoconvert \
! vp8enc min_quantizer=4 max_quantizer=13 cpu-used=2 deadline=500000 sharpness=0 target-bitrate=15000 threads=2  \
! queue max-size-buffers=0 max-size-time=0 max-size-bytes=0  \
! mux. pulsesrc device="alsa_input.usb-0c76_USB_PnP_Audio_Device-00.analog-mono" \
! audioconvert  \
! vorbisenc  \
! queue max-size-buffers=0 max-size-time=0 max-size-bytes=0  \
! mux. webmmux name=mux \
! filesink location=screencast.webm
```
_**Ctrl ^ c** to stop recording_

**Comment by brittadams** [comment]
0:00:00.038426352  2139 0x56009e7c6ed0 WARN     GST_ELEMENT_FACTORY gstelementfactory.c:456:gst_element_factory_make: no such element factory "pulsesrc"!
0:00:00.038469229  2139 0x56009e7c6ed0 ERROR           GST_PIPELINE grammar.y:816:priv_gst_parse_yyparse: no element "pulsesrc"
0:00:00.038904074  2139 0x56009e7c6ed0 ERROR           GST_PIPELINE grammar.y:901:priv_gst_parse_yyparse: link has no source [sink=@0x56009e8da3d0]
WARNING: erroneous pipeline: no element "pulsesrc"

**Comment by iacopodeenosee** [comment]
What is the output of `gst-inspect-1.0 pulsesrc` ?

**Comment by brittadams** [comment]
gst-inspect-1.0 pulsesrc
Factory Details:
  Rank                     primary + 10 (266)
  Long-name                PulseAudio Audio Source
  Klass                    Source/Audio
  Description              Captures audio from a PulseAudio server
  Author                   Lennart Poettering

Plugin Details:
  Name                     pulseaudio
  Description              PulseAudio plugin library
  Filename                 /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstpulseaudio.so
  Version                  1.12.1
  License                  LGPL
  Source module            gst-plugins-good
  Source release date      2017-06-20
  Binary package           GStreamer Good Plugins (Debian)
  Origin URL               http://packages.qa.debian.org/gst-plugins-good1.0

GObject
 +----GInitiallyUnowned
       +----GstObject
             +----GstElement
                   +----GstBaseSrc
                         +----GstPushSrc
                               +----GstAudioBaseSrc
                                     +----GstAudioSrc
                                           +----GstPulseSrc

Implemented Interfaces:
  GstStreamVolume

Pad Templates:
  SRC template: 'src'
    Availability: Always
    Capabilities:
      audio/x-raw
                 format: { (string)S16LE, (string)S16BE, (string)F32LE, (string)F32BE, (string)S32LE, (string)S32BE, (string)S24LE, (string)S24BE, (string)S24_32LE, (string)S24_32BE, (string)U8 }
                 layout: interleaved
                   rate: [ 1, 2147483647 ]
               channels: [ 1, 32 ]
      audio/x-alaw
                   rate: [ 1, 2147483647 ]
               channels: [ 1, 32 ]
      audio/x-mulaw
                   rate: [ 1, 2147483647 ]
               channels: [ 1, 32 ]


Element Flags:
  no flags set

Element Implementation:
  Has change_state() function: gst_pulsesrc_change_state

Clocking Interaction:
  element is supposed to provide a clock but returned NULL
Element has no URI handling capabilities.

Pads:
  SRC: 'src'
    Pad Template: 'src'

Element Properties:
  name                : The name of the object
                        flags: readable, writable
                        String. Default: "pulsesrc0"
  parent              : The parent of the object
                        flags: readable, writable
                        Object of type "GstObject"
  blocksize           : Size in bytes to read per buffer (-1 = default)
                        flags: readable, writable
                        Unsigned Integer. Range: 0 - 4294967295 Default: 0 
  num-buffers         : Number of buffers to output before sending EOS (-1 = unlimited)
                        flags: readable, writable
                        Integer. Range: -1 - 2147483647 Default: -1 
  typefind            : Run typefind before negotiating
                        flags: readable, writable
                        Boolean. Default: false
  do-timestamp        : Apply current stream time to buffers
                        flags: readable, writable
                        Boolean. Default: false
  buffer-time         : Size of audio buffer in microseconds. This is the maximum amount of data that is buffered in the device and the maximum latency that the source reports. This value might be ignored by the element if necessary; see "actual-buffer-time"
                        flags: readable, writable
                        Integer64. Range: 1 - 9223372036854775807 Default: 200000 
  latency-time        : The minimum amount of data to read in each iteration in microseconds. This is the minimum latency that the source reports. This value might be ignored by the element if necessary; see "actual-latency-time"
                        flags: readable, writable
                        Integer64. Range: 1 - 9223372036854775807 Default: 10000 
  actual-buffer-time  : Actual configured size of audio buffer in microseconds
                        flags: readable
                        Integer64. Range: -1 - 9223372036854775807 Default: -1 
  actual-latency-time : Actual configured audio latency in microseconds
                        flags: readable
                        Integer64. Range: -1 - 9223372036854775807 Default: -1 
  provide-clock       : Provide a clock to be used as the global pipeline clock
                        flags: readable, writable
                        Boolean. Default: true
  slave-method        : Algorithm used to match the rate of the masterclock
                        flags: readable, writable
                        Enum "GstAudioBaseSrcSlaveMethod" Default: 2, "skew"
                           (0): resample         - GST_AUDIO_BASE_SRC_SLAVE_RESAMPLE
                           (1): re-timestamp     - GST_AUDIO_BASE_SRC_SLAVE_RE_TIMESTAMP
                           (2): skew             - GST_AUDIO_BASE_SRC_SLAVE_SKEW
                           (3): none             - GST_AUDIO_BASE_SRC_SLAVE_NONE
  server              : The PulseAudio server to connect to
                        flags: readable, writable
                        String. Default: null
  device              : The PulseAudio source device to connect to
                        flags: readable, writable
                        String. Default: null
  device-name         : Human-readable name of the sound device
                        flags: readable
                        String. Default: null
  current-device      : The current PulseAudio source device
                        flags: readable
                        String. Default: ""
  client-name         : The PulseAudio client_name_to_use
                        flags: readable, writable, changeable only in NULL or READY state
                        String. Default: "gst-inspect-1.0"
  stream-properties   : list of pulseaudio stream properties
                        flags: readable, writable
                        Boxed pointer of type "GstStructure"
  source-output-index : The index of the PulseAudio source output corresponding to this record stream
                        flags: readable
                        Unsigned Integer. Range: 0 - 4294967295 Default: 4294967295 
  volume              : Linear volume of this stream, 1.0=100%
                        flags: readable, writable
                        Double. Range:               0 -              10 Default:               1 
  mute                : Mute state of this stream
                        flags: readable, writable
                        Boolean. Default: false

**Comment by iacopodeenosee** [comment]
the pulse audio plugin is correctly installed, can you record a screencast without sound?

**Comment by brittadams** [comment]
Yes able to record without sound

**Comment by brittadams** [comment]
There were some updates a few days later that seem to have resolved the issue.

**Comment by iacopodeenosee** [comment]
@brittadams  is https://github.com/EasyScreenCast/EasyScreenCast/issues/120 also solved?

**Comment by brittadams** [comment]
I did not open that one but was having the same issues. seems fine now
