### ISSUE TITLE
Unable to record anything

### ISSUE THREAD

**Issue by the-money-store** [EasyScreenCast/EasyScreenCast#149]
## Expected Behavior
I am trying to record my whole screen on Kali Linux 2017.1. I want the video output to be mkv, but I've tried with other formats and encountered the same error. I am also trying to use my headset audio to record, but had the same error regardless of using it or my built-in microphone. I'm pretty confident the problem is I'm missing some software or have a bad installation, which must be recent, because I was able to record videos just fine two weeks ago.
## Current Behavior
ERROR RECORDER - See logs for more info

## Steps to Reproduce (for bugs)
1. Have the most current Kali version, with all packages up to date
2. Click Start recording (it happens regardless of options selected)

## Logs
Current log error message: 
kali gnome-shell[1095]: JS LOG: [ESC]-#-mixer exist -> [object instance proxy GIName:Gvc.MixerControl jsobj@0x7f323f09db50 native@0x55de5efa1b80] state -> 1
## Your Environment
* Where did you download the extension?
 [ ] Gnome shell extension website
 [ ] From Git (Add commit tag)
Came included with Kali by default
* Gnome shell version:
3.22.3
* Operating System and version:
Kali Linux 2017.1
* Wayland or X?
X11

**Comment by brittadams** [comment]
I submitted https://github.com/EasyScreenCast/EasyScreenCast/issues/146 for not being able to record when any audio source is selected, sounds like you are having similar issues.

**Comment by iacopodeenosee** [comment]
Is a problem that comes with kali, when you try to record in MKV format you need the mkv continer, x264 encoder video and flac encoder audio, what does the execution of this command **[1]** return?
I'll contact the maintainer packet to speed up the resolution of this problem.
**[1]**
`gst-inspect-1.0 --plugin | grep "mkv\|x264\|pulsesrc\|flac"`

**Comment by the-money-store** [comment]
I'm not sure what changed between yesterday and today, but everything's working fine. I can record in any format with any audio input now. I tried the command and it said the command isn't found
