### ISSUE TITLE
Record chaos with a select window or area

### ISSUE THREAD

**Issue by colben** [EasyScreenCast/EasyScreenCast#150]
# Record chaos with a select window or area

## Expected Behavior
Record normally with a select window or area.

## Current Behavior
It records normally with all desktop and a select monitor, but record a mess with a select window or area.

## Possible Solution
Have no idea ...

## Steps to Reproduce (for bugs)
1.[Normal with all desktop and a select monitor](http://i1.buimg.com/600088/de41d7e11038f70c.png)
2.[Failed with a select window or a area](http://i1.buimg.com/600088/eb07af45e0a0114b.png)

## Logs
7月 08 19:44:21 ARK gnome-shell[691]: [ESC]-&-start video recording
7月 08 19:44:21 ARK gnome-shell[691]: [ESC]-§-get file extension C-> 1
7月 08 19:44:21 ARK gnome-shell[691]: [ESC]-§-COMPOSE GSP
7月 08 19:44:21 ARK gnome-shell[691]: [ESC]-#-mixer _init
7月 08 19:44:21 ARK gnome-shell[691]: [ESC]-#-mixer exist -> [object instance proxy GIName:Gvc.MixerControl jsobj@0x7f2d08020e80 native@0x39434c0] state -> 1
7月 08 19:44:21 ARK gnome-shell[691]: [ESC]-§-get option||devW: 0||devA: 0||Qgsp: 1||Qwc: ||Res: 0||Cont: 1
7月 08 19:44:21 ARK gnome-shell[691]: [ESC]-§-SCREEN
7月 08 19:44:21 ARK gnome-shell[691]: [ESC]-§-final GSP : vp9enc min_quantizer=4 max_quantizer=13 cpu-used=2 deadline=500000 sharpness=0 target-bitrate=15000 threads=%T ! queue max-size-buffers=0 max-size-time=0 max-size-bytes=0 ! webmmux
7月 08 19:44:21 ARK gnome-shell[691]: [ESC]-&-path/file template : Screencast_%d_%t.webm
7月 08 19:44:21 ARK org.gnome.Shell.desktop[691]: Recording to /home/noah/视频/Screencast_2017年07月08日_19时44分21秒.webm
7月 08 19:44:21 ARK gnome-shell[691]: [ESC]-&-screencast execute - true - /home/noah/视频/Screencast_2017年07月08日_19时44分21秒.webm
7月 08 19:44:21 ARK gnome-shell[691]: [ESC]-£-area recording init
7月 08 19:44:21 ARK gnome-shell[691]: [ESC]-£-draw area recording
7月 08 19:44:21 ARK gnome-shell[691]: [ESC]-*-record OK
7月 08 19:44:21 ARK gnome-shell[691]: [ESC]-*-replace STD indicator
7月 08 19:44:21 ARK gnome-shell[691]: [ESC]-*-show notify
7月 08 19:44:21 ARK gnome-shell[691]: [ESC]-°-create notify :Start Recording
7月 08 19:44:21 ARK gnome-shell[691]: Trying to re-add source 系统信息
7月 08 19:44:21 ARK gnome-shell[691]: [ESC]-%-init TimerCounting called
7月 08 19:44:21 ARK gnome-shell[691]: [ESC]-%-setcallback TimerCounting called
7月 08 19:44:21 ARK gnome-shell[691]: [ESC]-%-start TimerCounting called
7月 08 19:44:21 ARK gnome-shell[691]: [ESC]-*-update abs file path -> /home/noah/视频/Screencast_2017年07月08日_19时44分21秒.webm
7月 08 19:44:21 ARK gnome-shell[691]: [ESC]-*-refresh indicator -A true -F undefined
7月 08 19:44:22 ARK gnome-shell[691]: [ESC]-%-continued TimerCounting | sec: 1
7月 08 19:44:22 ARK gnome-shell[691]: [ESC]-°-update notify
7月 08 19:44:23 ARK gnome-shell[691]: [ESC]-%-continued TimerCounting | sec: 2
7月 08 19:44:23 ARK gnome-shell[691]: [ESC]-°-update notify
7月 08 19:44:24 ARK gnome-shell[691]: [ESC]-%-continued TimerCounting | sec: 3
7月 08 19:44:24 ARK gnome-shell[691]: [ESC]-°-update notify
7月 08 19:44:25 ARK gnome-shell[691]: [ESC]-%-continued TimerCounting | sec: 4
7月 08 19:44:25 ARK gnome-shell[691]: [ESC]-°-update notify
7月 08 19:44:26 ARK gnome-shell[691]: [ESC]-%-continued TimerCounting | sec: 5
7月 08 19:44:26 ARK gnome-shell[691]: [ESC]-°-update notify
7月 08 19:44:27 ARK gnome-shell[691]: [ESC]-%-continued TimerCounting | sec: 6
7月 08 19:44:27 ARK gnome-shell[691]: [ESC]-°-update notify
7月 08 19:44:28 ARK gnome-shell[691]: [ESC]-%-continued TimerCounting | sec: 7
7月 08 19:44:28 ARK gnome-shell[691]: [ESC]-°-update notify
7月 08 19:44:29 ARK gnome-shell[691]: [ESC]-*-refresh indicator -A true -F true
7月 08 19:44:29 ARK gnome-shell[691]: [ESC]-*-refresh indicator -A true -F false
7月 08 19:44:29 ARK gnome-shell[691]: [ESC]-*-refresh indicator -A true -F true
7月 08 19:44:29 ARK gnome-shell[691]: [ESC]-%-continued TimerCounting | sec: 8
7月 08 19:44:29 ARK gnome-shell[691]: [ESC]-°-update notify
7月 08 19:44:30 ARK gnome-shell[691]: [ESC]-%-continued TimerCounting | sec: 9
7月 08 19:44:30 ARK gnome-shell[691]: [ESC]-°-update notify
7月 08 19:44:31 ARK gnome-shell[691]: [ESC]-%-continued TimerCounting | sec: 10
7月 08 19:44:31 ARK gnome-shell[691]: [ESC]-°-update notify
7月 08 19:44:32 ARK gnome-shell[691]: [ESC]-%-continued TimerCounting | sec: 11
7月 08 19:44:32 ARK gnome-shell[691]: [ESC]-°-update notify
7月 08 19:44:33 ARK gnome-shell[691]: [ESC]-%-continued TimerCounting | sec: 12
7月 08 19:44:33 ARK gnome-shell[691]: [ESC]-°-update notify
7月 08 19:44:34 ARK gnome-shell[691]: [ESC]-*-right click indicator
7月 08 19:44:34 ARK gnome-shell[691]: [ESC]-*-stop recording
7月 08 19:44:34 ARK gnome-shell[691]: [ESC]-&-stop video recording
7月 08 19:44:34 ARK gnome-shell[691]: [ESC]-*-refresh indicator -A false -F undefined
7月 08 19:44:34 ARK gnome-shell[691]: [ESC]-&-screencast stop - true
7月 08 19:44:34 ARK gnome-shell[691]: [ESC]-£-hide area recording
7月 08 19:44:34 ARK gnome-shell[691]: [ESC]-£-draw area recording
7月 08 19:44:34 ARK gnome-shell[691]: [ESC]-%-finish TimerCounting 
7月 08 19:44:34 ARK gnome-shell[691]: [ESC]-°-update notify
7月 08 19:44:34 ARK gnome-shell[691]: [ESC]-%-stop TimerCounting called
7月 08 19:44:34 ARK gnome-shell[691]: [ESC]-*-refresh indicator -A false -F false

## Your Environment
* Where did you download the extension?
 [ ] Gnome shell extension website
 [*] From Git (Add commit tag)
* Gnome shell version:
3.24.2-1
* Operating System and version:
Arch Linux - Lastet version
* Wayland or X?
X

**Comment by iacopodeenosee** [comment]
can you show the part of the log where it calculates the size of the area to be recorded?

**Comment by colben** [comment]
Sorry for missing your notes! Now I'm using "green recorder" in archlinux ...
