### ISSUE TITLE
[query] What does the shortcut key do?

### ISSUE THREAD

**Issue by kwill** [EasyScreenCast/EasyScreenCast#152]
Under Options I have "Enable keyboard shortcut" on, and the shortcut key set to "Super+E" (the default). However, nothing happens when I press that combo before recording or during recording. What behavior should I be seeing?

## Your Environment
* Where did you download the extension? Gnome shell extension website
* Gnome shell version: 3.24.2
* Operating System and version: Ubuntu 17.04
* Display server: X11

**Comment by iacopodeenosee** [comment]
It would be helpful see the log, try to change the key combination, maybe SUPER + E is already registered, or restore the default settings.

**Comment by kwill** [comment]
Must have been me :P It triggers recording as expected (including a delay). If recording is underway, it stops recording.
