### ISSUE TITLE
[feature] Execute command before recording

### ISSUE THREAD

**Issue by kwill** [EasyScreenCast/EasyScreenCast#153]
**User story:** I am a regular screencaster. I want to automate cleaning up my desktop before recording, so that I can quickly and consistently have the same environment every time I record.

## Expected Behavior
* An option to set a pre-recording script.

## Current Behavior
* There is currently no such feature.
* There is a similar feature for post-recording.

## Possible Solution
* Open Preferences
* Under options enable "Execute command before recording"
* Enter command to execute
* When recording is invoked, this command is executed and must exit successfully before recording actually starts
  * If there is a delay enabled, the delay should be timed from when the script ends.
  * If the script fails, recording should not start and a simple notification given ("Recording startup script failed. Please correct the error and try again.").

## Your Environment
* Where did you download the extension? Gnome shell extension website
* Gnome shell version: 3.24.2
* Operating System and version: Ubuntu 17.04
* Display server: X11

**Comment by iacopodeenosee** [comment]
I do not see big problems except to find the time to do it :)
