### ISSUE TITLE
[feature] Visualise the delay

### ISSUE THREAD

**Issue by kwill** [EasyScreenCast/EasyScreenCast#154]
## Expected Behavior
* When I have set a delay and I start recording, I should be aware when the delay has ended and the recording starts.

## Current Behavior
* When I have set a delay and I start recording, the camera icon goes red immediately. There is no change after the delay period.

## Possible Solution
When I have set a delay and I start recording:
 * the camera turns amber
 * a numeric countdown (also amber) appears next to the camera
 * at five seconds, the countdown and camera turn red
 * at zero seconds, the countdown is removed and the camera remains red

## Your Environment
* Where did you download the extension? Gnome shell extension website
* Gnome shell version: 3.24.2
* Operating System and version: Ubuntu 17.10
* Display server: X11

**Comment by iacopodeenosee** [comment]
The registration delay is not respected? Can you post the log?

**Comment by kwill** [comment]
This must have been me. The extension works almost exactly as described: there's a delay, then the camera turns red to indicate recording.
