### ISSUE TITLE
[feature] Option to hide the camera icon while recording

### ISSUE THREAD

**Issue by kwill** [EasyScreenCast/EasyScreenCast#155]
## Expected Behavior
* When I create a screencast, it looks like a "normal" desktop and doesn't include the camera icon. (Which a viewer might get confused or distracted by.)

## Current Behavior
* The camera icon appears in the screencast.

## Possible Solution
* When recording, the camera icon disappears.
* ~~Recording stops with a keyboard combo.~~ (already implemented)

## Your Environment
* Where did you download the extension? Gnome shell extension website
* Gnome shell version: 3.24.2
* Operating System and version: Ubuntu 17.10
* Display server: X11

**Comment by iacopodeenosee** [comment]
i think that there is not problem to implementing it
