### ISSUE TITLE
[query] How to activate extension from the command line?

### ISSUE THREAD

**Issue by kwill** [EasyScreenCast/EasyScreenCast#157]
I am a user with scripting abilities. I want to write a script that activates the EasyScreenCast extension, so that I can coordinate multiples actions with a single command. (This is to activate the extension, not to start/stop recording.)

## Expected Behavior
* In GNOME Tweak, enable EasyScreenCast.
* Camera icon appears in top bar.
* From the command line, invoke `gnome-shell-extension-tool --disable-extension=EasyScreenCast`
* Should remove EasyScreenCast from the top bar.
* Similarly, if ESC is not active, `gnome-shell-extension-tool --enable-extension=EasyScreenCast` should activate the extension.

## Current Behavior

`gnome-shell-extension-tool --disable-extension=EasyScreenCast` results in an error message `'EasyScreenCast' is not enabled or installed.`

`gnome-shell-extension-tool --enable-extension=EasyScreenCast` returns the message `'EasyScreenCast' is now enabled.` but it does not appear in the top bar, and is not enabled in GNOME Tweak.

## Possible Solution
Maybe this isn't the job of `gnome-shell-extension-tool`? If not, is there some other way to activate/deactivate the extension?

## Your Environment
* Where did you download the extension? Gnome shell extension website
* Gnome shell version: 3.24.2
* Operating System and version: Ubuntu 17.04
* Display server: X11

**Comment by iacopodeenosee** [comment]
@kwill have you try the command with the complete UUID of the extension?
`gnome-shell-extension-tool -d EasyScreenCast@iacopodeenosee.gmail.com`
this works for me

**Comment by kwill** [comment]
That worked. Thanks!
