### ISSUE TITLE
Cannot record Remmina Window of an RDP session

### ISSUE THREAD

**Issue by gregoliver** [EasyScreenCast/EasyScreenCast#158]
## Expected Behavior
It should record liks all of my other windows - maybe a remmina bug?

## Current Behavior
ERROR RECORDER

## Steps to Reproduce (for bugs)
1.  Try recording a selective remmina window  
2.
3.
4.

## Logs
Jul 27 13:12:20 dell-wifi gnome-shell[1491]: JS LOG: [ESC]-£-window highlight on, pos/meas: x:1955 y:37 w:1649 h:1049
Jul 27 13:12:20 dell-wifi gnome-shell[1491]: JS LOG: [ESC]-£-capture selection stop
Jul 27 13:12:20 dell-wifi gnome-shell[1491]: JS LOG: [ESC]-£-windows pre wx: 1955 wy: 37 height: 1049  width: 1649
Jul 27 13:12:20 dell-wifi gnome-shell[1491]: JS LOG: [ESC]-£-windows post wx: 1955 wy: 37 height: 1043 width: -35
Jul 27 13:12:20 dell-wifi gnome-shell[1491]: JS LOG: [ESC]-£-selection x:1955 y:37 height:1043 width:-35
Jul 27 13:12:20 dell-wifi gnome-shell[1491]: JS LOG: [ESC]-*-instant recording called
Jul 27 13:12:20 dell-wifi gnome-shell[1491]: JS LOG: [ESC]-&-start video recording
Jul 27 13:12:20 dell-wifi gnome-shell[1491]: JS LOG: [ESC]-§-get file extension C-> 2
Jul 27 13:12:20 dell-wifi gnome-shell[1491]: JS LOG: [ESC]-§-COMPOSE GSP
Jul 27 13:12:20 dell-wifi gnome-shell[1491]: JS LOG: [ESC]-#-mixer _init
Jul 27 13:12:20 dell-wifi gnome-shell[1491]: JS LOG: [ESC]-#-mixer exist -> [object instance proxy GIName:Gvc.MixerControl jsobj@0x7fde90f2e9d0 native@0x563f77a0acf0] state -> 1
Jul 27 13:12:20 dell-wifi gnome-shell[1491]: JS LOG: [ESC]-§-get option||devW: 0||devA: 0||Qgsp: 1||Qwc: ||Res: 2||Cont: 2
Jul 27 13:12:20 dell-wifi gnome-shell[1491]: JS LOG: [ESC]-§-SCREEN
Jul 27 13:12:20 dell-wifi gnome-shell[1491]: JS LOG: [ESC]-§-final GSP :videoscale ! video/x-raw, width=1280, height=720, add-borders=true !  x264enc psy-tune="animation" speed-preset="fast" subme=5 qp-min=18 qp-max=28 threads=%T ! queue max-size-buffers=0 max-size-time=0 max-size-bytes=0 ! mp4mux
Jul 27 13:12:20 dell-wifi gnome-shell[1491]: JS LOG: [ESC]-&-path/file template : Screencast_%d_%t.mp4
Jul 27 13:12:20 dell-wifi gnome-shell[1491]: JS LOG: [ESC]-&-ERROR(screencast execute) - GDBus.Error:org.gtk.GDBus.UnmappedGError.Quark._g_2dio_2derror_2dquark.Code19: Invalid params
Jul 27 13:12:20 dell-wifi gnome-shell[1491]: JS LOG: [ESC]-&-stop video recording
Jul 27 13:12:20 dell-wifi gnome-shell[1491]: JS LOG: [ESC]-*-record ERROR
Jul 27 13:12:20 dell-wifi gnome-shell[1491]: JS LOG: [ESC]-*-show error notify
Jul 27 13:12:20 dell-wifi gnome-shell[1491]: JS LOG: [ESC]-°-create notify :ERROR RECORDER - See logs for more info

## Your Environment
 [ ] Gnome shell extension website
* Gnome shell version:
3.22.3
* Operating System and version:
Fedora 25
* Display server: Wayland / X11 / Other
X11 (cannot switch to Wayland yet)

**Comment by iacopodeenosee** [comment]
hi, i think the problem is in the window selection, ESC can not start recording because some parameters are negative:

> Jul 27 13:12:20 dell-wifi gnome-shell[1491]: JS LOG: [ESC]-£-selection x:1955 y:37 height:1043 width:-35

You have two solutions, first one use the latest version from **master git repo**, for what I remember that problem should have been solved; the second is the fastest, instead of selecting the window, you can select the area of recording by choosing the **Record a selected area** or even the full desktop.

**Comment by gregoliver** [comment]
Thanks, I can confirm both of your suggestions work.  master is best since I alwasy want to recrod a single app usually.
