### ISSUE TITLE
Can't open preferences menu

### ISSUE THREAD

**Issue by H0nus** [EasyScreenCast/EasyScreenCast#161]
I can't open preferences menu

## Expected Behavior
I try to open preferences menu

## Current Behavior
Instead of opening the menu, i got an error, with both github and Gnome shell extension website

## Steps to Reproduce (for bugs)
1.
2.
3.
4.

## Logs
Journalctl logs:
set 01 03:36:58 ath0s firefox.desktop[6553]:     receive@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/content/worker-child.js:87:7
set 01 03:36:58 ath0s firefox.desktop[6553]: emitOnObject@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:110:7
set 01 03:36:58 ath0s firefox.desktop[6553]: emit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:86:38
set 01 03:36:58 ath0s firefox.desktop[6553]: messageReceived@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/remote/child.js:67:37
set 01 03:39:41 ath0s firefox.desktop[6553]: Extension error: TypeError: tab.url is undefined moz-extension://16ce1b76-7253-4e9e-9aa5-c920ba18546f/js/tabManager.js 91
set 01 03:39:41 ath0s firefox.desktop[6553]: @moz-extension://16ce1b76-7253-4e9e-9aa5-c920ba18546f/js/tabManager.js:91:1
set 01 03:39:41 ath0s firefox.desktop[6553]: runSafeSyncWithoutClone@resource://gre/modules/ExtensionUtils.jsm:54:129
set 01 03:39:41 ath0s firefox.desktop[6553]: runSafeWithoutClone@resource://gre/modules/ExtensionCommon.jsm:176:38
set 01 03:39:41 ath0s firefox.desktop[6553]: receiveMessage@resource://gre/modules/ExtensionChild.jsm:763:61
set 01 03:39:41 ath0s firefox.desktop[6553]: _callHandlers/<@resource://gre/modules/MessageChannel.jsm:585:17
set 01 03:39:41 ath0s firefox.desktop[6553]: _callHandlers@resource://gre/modules/MessageChannel.jsm:584:14
set 01 03:39:41 ath0s firefox.desktop[6553]: _handleMessage/deferred.promise<@resource://gre/modules/MessageChannel.jsm:649:7
set 01 03:39:41 ath0s firefox.desktop[6553]: _handleMessage@resource://gre/modules/MessageChannel.jsm:646:24
set 01 03:39:41 ath0s firefox.desktop[6553]: receiveMessage@resource://gre/modules/MessageChannel.jsm:163:5
Shell backtrace:
GLib.SpawnError: Esecuzione del processo figlio «xdg-user-dir» non riuscita (No such file or directory)

Stack trace:
  getResultCmd@/home/ivan/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/convenience.js:107
  EasyScreenCastSettingsWidget<._init@/home/ivan/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/prefs.js:296
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178
  buildPrefsWidget@/home/ivan/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/prefs.js:633
  Application<._selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:90
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178
  Application<._onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:239
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178
  main@resource:///org/gnome/shell/extensionPrefs/main.js:377
  @<main>:1
  

## Your Environment
Tried both shell
 [ +] Gnome shell extension website
 [ +] From Git (Add commit tag)
* Gnome shell version: GNOME Shell 3.22.3

* Operating System and version: Debian 9

* Display server: X11

**Comment by iacopodeenosee** [comment]
hi, what results if you execute this [ `xdg-user-dir VIDEOS` ] in the terminal?

**Comment by H0nus** [comment]
i don't know how, but i reinstalled my os and now it works, but i can't record in mp4 format, and i have installed all gstreamer plugins.

**Comment by iacopodeenosee** [comment]
can you execute this [1] in the terminal? simple try to record the desktop and save it into a mp4 file using x264 encoder; return some errors?
[1] 
```
gst-launch-1.0  --gst-debug=3 \
ximagesrc \
! videoconvert \
! x264enc tune="fastdecode" speed-preset="superfast" subme=1 qp-min=28 qp-max=40 \
! mp4mux name=mux \
! filesink location=scr.mp4
```
