### ISSUE TITLE
On hover background too big for panel icon.

### ISSUE THREAD

**Issue by kathenas** [EasyScreenCast/EasyScreenCast#162]
On hover background too big for panel icon.

Screenshot of issue when using Arc theme.

![screenshot from 2017-09-01 03-41-40](https://user-images.githubusercontent.com/30290647/29953539-1b859380-8ec9-11e7-91aa-0864e8ecafcd.png)

Diff:

```
diff --git a/extension.js b/extension.js
index fdc3fc5..da56e9f 100644
--- a/extension.js
+++ b/extension.js
@@ -91,7 +91,7 @@ const EasyScreenCast_Indicator = new Lang.Class({
         });
         this.timeLabel = new St.Label({
             text: "",
-            style_class: 'time-label',
+            style_class: 'popup-menu-icon',
             y_expand: true,
             y_align: Clutter.ActorAlign.CENTER
         });
```

Screenshot after fix:

![screenshot from 2017-09-01 03-44-04](https://user-images.githubusercontent.com/30290647/29953633-c8567f5c-8ec9-11e7-8105-bca50af1bbe1.png)

**Comment by iacopodeenosee** [comment]
hi, with this change we lose the color of the timer and right margin, it would be better to change the css property [ `.time.label -> margin-right` ] via code when the timer is activated. If you have time and desire to make a PR you are welcome. thx
