### ISSUE TITLE
shortcut to record and stop isn't working

### ISSUE THREAD

**Issue by juusechec** [EasyScreenCast/EasyScreenCast#165]
I've change the configuration to many shortcuts but no of them working. What is the command to initiate directly in Gnome shortcuts configuration?

**Comment by iacopodeenosee** [comment]
hi, you can reset all options with the relative button on UI preferences, and then try to use <SUPER> + <E> Key combinations, if this doesn't work provide logs so we can solve this problem.
It would also be useful to know other informations, like distro, gnome shell version and key combination you tried. thx

**Comment by juusechec** [comment]
How i can see logs of this plugin?

**Comment by iacopodeenosee** [comment]
@juusechec see here -> https://github.com/EasyScreenCast/EasyScreenCast#how-to-view-the-logs
you need to enable the **verbose log** via the relative button (into window preference), however try this:

1. reset all the options via the relative button (into window preference)
2. reload the extension (retart gnome-shell)
3. try to use the default key combination (SUPER + E)

**Comment by juusechec** [comment]
Hi, I try the process (again) but for all tabs, and now it's working. The process to **verbose log** isn't working, only have an empty response of command as normal user and as root. Thanks!
