### ISSUE TITLE
Error when trying to record 

### ISSUE THREAD

**Issue by MarilenePelayo** [EasyScreenCast/EasyScreenCast#166]
Just installed the extension then tried to record without success. Log shows error on utilrecorder.js 
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Logs

 * Use `journalctl /usr/bin/gnome-shell -f` to monitor Gnome shell activity. Maybe the crash will log something.
[journal2.txt](https://github.com/EasyScreenCast/EasyScreenCast/files/1354230/journal2.txt)

 * Log, **enable verbose debug logs** into options window, and after that try  
 `journalctl --since=today --no-pager | grep js`
[journal1.txt](https://github.com/EasyScreenCast/EasyScreenCast/files/1354231/journal1.txt)
 * webcam info:
 `v4l2-ctl --all`
 * webcam info:
 `for VIDEO_DEVICE in /dev/video* ; do echo ; echo ; echo $VIDEO_DEVICE ; echo ; v4l2-ctl --device=$VIDEO_DEVICE --list-inputs ; done`
 * webcam info:
 `GST_DEBUG=v4l2src:5 gst-launch-1.0 v4l2src num-buffers=1 ! fakesink | grep probed`

## Your Environment

* Where did you download the extension?
 [X ] Gnome shell extension website
 [ ] From Git (Add commit tag)
* Gnome shell version:
GNOME Shell 3.14.4
* Operating System and version:
Red Hat Enterprise Linux Workstation 7.3
* Display server: Wayland / X11 / Other

**Comment by iacopodeenosee** [comment]
hi, this is a 2 years old version, it's hard for me to debug this, i think you can install this version [1], it's the first version compatible with gnome shell version 3.14, or if you can upgrade gnome shell to 3.16 version you could use the latest version of the extension. thx

[1] https://extensions.gnome.org/review/download/4417.shell-extension.zip

**Comment by MarilenePelayo** [comment]
Thank you for your help. I'll try to install the old version first.

**Comment by MarilenePelayo** [comment]
@iacopodeenosee I had the oldest version installed and I'm facing the same error :(

Out 05 13:19:35 oc8340078324.ibm.com gnome-session[2442]: (gnome-shell:3027): Gjs-WARNING ****: **JS ERROR: TypeError: this.updateGSP is not a function****
Out 05 13:19:35 oc8340078324.ibm.com gnome-session[2442]: CaptureVideo<.start@/home/marimu/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/utilrecorder.js:72

 ... I think I'll have to upgrade gnome shell
