### ISSUE TITLE
Request for a new release

### ISSUE THREAD

**Issue by ghisvail** [EasyScreenCast/EasyScreenCast#191]
I intend to provide a corresponding Debian package (`gnome-shell-extension-easyscreencast`) for `EasyScreenCast`. Would you consider releasing a new version (0.10.1? 0.11?) with the latest bug fixes and enhancements of the build system? Prior to the release, please consider merging #189 and #190 to facilitate the packaging effort.

**Comment by iacopodeenosee** [comment]
best wait tobias merging **all** the lasts PR
ping  @tobias47n9e

**Comment by tobias47n9e** [comment]
Two small patches still need a review (@iacopodeenosee I added you as a reviewer to the patches). I have been having stability issues with the extension system all around, so it is difficult for me to tell how stable ESC is at the moment. Let's hope for the best 😄

**Comment by ghisvail** [comment]
Thank you guys for looking into it.

**Comment by iacopodeenosee** [comment]
@tobias47n9e if you want to create the new release it's ok, **for me the two PR are fine**.
I think one solution to improve stability of the init extension is to move the pulseaudio(GVC) and gstreamer(GST) init into a [async](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function) function in this way we separate the gnome-shell process from the initialization of these libraries. what do you think? have you another idea?

**Comment by tobias47n9e** [comment]
I submitted the extension for review again today. It seems to have disappeared from the extension page

**Comment by tobias47n9e** [comment]
Extension published again (1.0.0) https://extensions.gnome.org/extension/690/easyscreencast/
