### ISSUE TITLE
kali 2018.1 not installable

### ISSUE THREAD

**Issue by Berechja** [EasyScreenCast/EasyScreenCast#192]
I downloaded today kali iso's by torrent from the original website. both files the small version 0.8 gb and the big version 2.9 gb are not able to install!
As soon it detect the cd / usb it claims it's not a valid debian installer.
Going into the live part of the cd / usb there is total no problem.
I really wish to install kali alongside windows 10 on my acer nitro 5.
I tried several ways of creating the bootable usb (in my case) rufus, universal installer and just format the usb as fat32 and then copy all contents from the mounted iso.
There is for me no way to find a way to install linux from the live usb. (i just do not know how to do and google aint a help in this matter.
please help me out

sincerely yours,

Berechja Kerkdijk

**Comment by tobias47n9e** [comment]
Sorry, but this repo is not the right place to ask this question. Try some Linux question chat I would recommend.
