### ISSUE TITLE
Gnome-Shell 3.28 crashes when turning on EasyScreenCast (extensions.gnome.org version)

### ISSUE THREAD

**Issue by bartoszek** [EasyScreenCast/EasyScreenCast#194]
## Disclaimer
> Git version seems to be working, the issue only applicable to version hosted on extensions.gnome.org

When turning on the extension form `gnome-shell-extensions-pref` screen freezes.

**Possible Solution**
For `gnome-shell` 3.26 removing `pipewire` fixes the issue, but version 3.28 makes `pipewire` implicit dependency of `mutter`, which render this solution no longer viable. 

**Logs**
`journalctl -b -1` log truncuted to moment of turning on the extension.
[log2.log](https://github.com/EasyScreenCast/EasyScreenCast/files/1845499/log2.log)
`coredumpctl info`:
[coredump.log](https://github.com/EasyScreenCast/EasyScreenCast/files/1845517/coredump.log)

 * webcam info: no webcam (/dev/video0 missing)

**Your Environment**
 [*] Gnome shell extension website
 [ ] From Git (Add commit tag)
* Gnome shell version: 3.28
* Operating System and version: Archlinux (kernel 4.15)
* Display server: X11 (xorg-server 1.19.6)

**Comment by bartoszek** [comment]
@letorbi Thanks for the tip, git version works for me too. I assume that gnome website pulls code directly from git without keeping its own version (silly me).

**Comment by letorbi** [comment]
@bartoszek Great I could help, but maybe we should keep this issue open until the version that is distributed by the shell extension website has been updated as well... If you agree, I'd suggest that you re-open this issue.

**Comment by letorbi** [comment]
@tobias47n9e It seems that you are responsible for the version distributed by the Gnome Extensions page. Am I right? If that's the case, it would be great if you could update the version of the Gnome Extensions page, so that this issue can be finally closed.

**Comment by tobias47n9e** [comment]
I just published the extension again: https://extensions.gnome.org/extension/690/easyscreencast/

Sorry for the delay. I wasn't aware that the extension page was outdated.
