### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by ghost** [EasyScreenCast/EasyScreenCast#200]
I'm not able to install your extension. Usually I pass by the gnome adds on on Firefox, but I got a broken link.

 https://extensions.gnome.org/extension/690/easyscreencast/

**Comment by tobias47n9e** [comment]
Not sure what happend there. I will try to publish it again

**Comment by kamrava** [comment]
404 page not found!

**Comment by mmusil** [comment]
@tobias47n9e, the link is still broken. Have you checked whether it works for you? :)

**Comment by tobias47n9e** [comment]
I thought the review was done, but actually it needs another change. Tried to submit 1.0.1 today

**Comment by tobias47n9e** [comment]
@mmusil Thanks for your patience. Will close again
