### ISSUE TITLE
404 on GNOME Extension Page

### ISSUE THREAD

**Issue by sherl0cks** [EasyScreenCast/EasyScreenCast#202]
https://extensions.gnome.org/extension/690/easyscreencast/
![screenshot from 2018-07-18 12-53-51](https://user-images.githubusercontent.com/1335137/42901733-a4e61598-8a89-11e8-9fcf-68cb3e15ce1d.png)

**Comment by tobias47n9e** [comment]
Sorry about that. Republishing and review of the extension are still ongoing.

**Comment by tobias47n9e** [comment]
Seems to be reviewed and online now
