### ISSUE TITLE
on open options menu

### ISSUE THREAD

**Issue by develhopper** [EasyScreenCast/EasyScreenCast#205]
when click on options in menu
## Expected Behavior

see options window
## Current Behavior

but show this logs
## Logs

SyntaxError: missing : after property id

Stack trace:
  Application<._getExtensionPrefsModule@resource:///org/gnome/shell/extensionPrefs/main.js:74
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178
  Application<._selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:89
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178
  Application<._onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:239
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178
  main@resource:///org/gnome/shell/extensionPrefs/main.js:377
  @<main>:1
  

## Your Environment

* Where did you download the extension?
 [* ] Gnome shell extension website
 [ ] From Git (Add commit tag)
* Gnome shell version:3.22.2

* Operating System and version: debian 9 stretch

* Display server:x11

**Comment by FDiskas** [comment]
Same for me
