### ISSUE TITLE
Not working on Fedora 29 - GNOME Shell 3.30.1

### ISSUE THREAD

**Issue by ashucg** [EasyScreenCast/EasyScreenCast#210]
## Expected Behavior

Should be able to select some area to be recorded
## Current Behavior

Freezes GNOME and I can't do anything on the windows, only mouse pointer appears to move but nothing happens when I try to select/close any window.
## Possible Solution

Not sure
## Steps to Reproduce (for bugs)

1. Install Fedora 29 - GNOME Shell 3.30.1
2. Use X11 display server for GNOME sessions
3. Install and activate the extension
4. Try to create a new screencast

## Logs
```
Some code accessed the property 'SelectionArea' on the module 'selection'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
[ESC]-£-area selection init
[ESC]-£-capture selection init
JS WARNING: [/home/ashutosh/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/selection.js 115]: reference to undefined property "screen"
JS ERROR: TypeError: global.screen is undefined
_setCaptureCursor@/home/ashutosh/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/selection.js:115:9
wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
_init@/home/ashutosh/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/selection.js:89:13
wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
_Base.prototype._construct@resource:///org/gnome/gjs/modules/_legacy.js:18:5
newClass@resource:///org/gnome/gjs/modules/_legacy.js:114:32
_init@/home/ashutosh/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/selection.js:213:25
wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
_Base.prototype._construct@resource:///org/gnome/gjs/modules/_legacy.js:18:5
newClass@resource:///org/gnome/gjs/modules/_legacy.js:114:32
_doRecording@/home/ashutosh/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/extension.js:631:25
wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
_onButtonPress@/home/ashutosh/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/extension.js:212:13
wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
_init/<@/home/ashutosh/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/extension.js:86:31
```

## Your Environment

* Where did you download the extension?
 [x] Gnome shell extension website
 [ ] From Git (Add commit tag)
* Gnome shell version: 3.30.1

* Operating System and version: Fedora 29

* Display server: X11

**Comment by ashucg** [comment]
Please see https://github.com/micheleg/dash-to-dock/pull/770#issue-199936075

**Comment by OOsemka** [comment]
I hit the same issue and worked it around with replacing all occurrences of global.screen. with global.display.  and it's not working for me fine .. the proper fix would be to define condition that will change this based on gnome shell version

**Comment by simonbcn** [comment]
Same problem on Arch Linux with GNOME Shell 3.30.1 on Wayland.

**Comment by jmtorresc** [comment]
This patch should work [patch for gnome 3.30 with Backward compatibility](http://jamonete.org/static/patches/easyscreencast-fix-gnome-shell-3.30.txt) based on [micheleg/dash-to-dock#770 (comment)](https://github.com/micheleg/dash-to-dock/pull/770#issue-199936075) mentioned by @ashucg

**Comment by traxtopel** [comment]
Works for me on Fedora 29.

**Comment by letorbi** [comment]
The latest commits (9519e64 & 3fca35f ) seem to have fixed the problem for X11, but not for Wayland. [See the latest comments in issue 211.](https://github.com/EasyScreenCast/EasyScreenCast/issues/211#ref-commit-9519e64)
