### ISSUE TITLE
Works only with "Record all desktop" option in Fedora 30

### ISSUE THREAD

**Issue by diegovasconcelos** [EasyScreenCast/EasyScreenCast#224]
Works only with "Record all desktop" option. If another option (e.g. "Record a selected window") is selected, not working. I've tested and tried with several different option combination, but the bug appeared every time I tried, except with "Record all desktop" option. 

## Logs

mai 01 16:35:48 fedora gnome-shell[1653]: JS ERROR: Exception in callback for signal: activate: TypeError: Shell.GenericContainer is not a constructor
                                          _init@/home/diego/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/selection.js:65:31
                                          wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22                                          _Base.prototype._construct@resource:///org/gnome/gjs/modules/_legacy.js:18:5
                                          newClass@resource:///org/gnome/gjs/modules/_legacy.js:114:32
                                          _init@/home/diego/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/selection.js:214:25
                                          wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22                                          _Base.prototype._construct@resource:///org/gnome/gjs/modules/_legacy.js:18:5
                                          newClass@resource:///org/gnome/gjs/modules/_legacy.js:114:32
                                          _doRecording@/home/diego/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/extension.js:636:25
                                          wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
                                          _add_start_stop_menu_entry/<@/home/diego/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/extension.js:270:17
                                          _emit@resource:///org/gnome/gjs/modules/signals.js:142:27
                                          activate@resource:///org/gnome/shell/ui/popupMenu.js:167:9                                       _onButtonReleaseEvent@resource:///org/gnome/shell/ui/popupMenu.js:118:9

## Your Environment
* Where did you download the extension?
Git (version 1.0.2)
* Gnome shell version:
3.32.1
* Operating System and version:
Fedora 30
* Display server:
Wayland and X11

**Comment by deathbyfreezeray** [comment]
I am experiencing the same thing in ubuntu 19.04, using the version on the Gnome Shell Extension Website. I have dual monitors.

**Comment by xavifr** [comment]
Same to me in ubuntu 19.04

**Comment by diegovasconcelos** [comment]
> Same to me in ubuntu 19.04
> 
> Replacing the use of **Shell.GenericContainer** (deprecated) with **St.Widget** in selection.js file solved the issue for me.
> 
> I don't know if it is a real/permanent solution, but at least it is a workaround...
> 
> ```
> --- selection.js.orig	2019-05-09 15:15:25.778361934 +0200
> +++ selection.js	2019-05-09 15:17:03.265325362 +0200
> @@ -62,7 +62,7 @@
>  
>          this.monitor = Main.layoutManager.focusMonitor;
>  
> -        this._areaSelection = new Shell.GenericContainer({
> +        this._areaSelection = new St.Widget({
>              name: 'area-selection',
>              style_class: 'area-selection',
>              visible: 'true',
> ```

works for me.

**Comment by timwetter** [comment]
this works for me in gnome-shell 3.32.


--- selection.js.orig	2019-05-09 15:15:25.778361934 +0200
+++ selection.js	2019-05-09 15:17:03.265325362 +0200
@@ -62,7 +62,7 @@
 
         this.monitor = Main.layoutManager.focusMonitor;
 
-        this._areaSelection = new Shell.GenericContainer({
+        this._areaSelection = new St.Widget({
             name: 'area-selection',
             style_class: 'area-selection',
             visible: 'true',


AND


@@ -408,9 +408,9 @@
 
 -     this._areaRecording = new Shell.GenericContainer({
 +    this._areaRecording = new St.Widget({

**Comment by peterjaap** [comment]
Conrifmed, works after patching and restarting gnome. Please merge!
