### ISSUE TITLE
Can not run after update Kali Linux

### ISSUE THREAD

**Issue by nu11secur1ty** [EasyScreenCast/EasyScreenCast#232]
After the update of Kali Linux, the easyscreen is not working.

**Comment by nu11secur1ty** [comment]
[easyscreen.log](https://github.com/EasyScreenCast/EasyScreenCast/files/3493836/easyscreen.log)

**Comment by security-kma** [comment]
hey bro. Did you fix it yet ???

**Comment by nu11secur1ty** [comment]
Yea everything is ok.
