### ISSUE TITLE
gnome 3.34 compatibility - No signal 'value-changed' on object Gjs_Slider

### ISSUE THREAD

**Issue by CircleCode** [EasyScreenCast/EasyScreenCast#237]
After update to gnome-shell 3.34, the extensions has the following error: `No signal 'value-changed' on object Gjs_Slider`

This seems to affect a lot of extensions with fixes like https://github.com/kiyui/gnome-shell-night-light-slider-extension/pull/49/files

**Comment by lverissimo** [comment]
@CircleCode you are a life saver! Very simple change

in line 520: changed 
        this.TimeSlider.connect(
            'value-changed', (item) => {
to:
        this.TimeSlider.connect(
            'notify::value', (item) => {

and it is now working. Don't ask me why, just googled based upon your tip.

**Comment by legluondunet** [comment]
Is the main dev still maintain this extension? There are two pull request to add Gnome 3.3X compatibility and no one validated it yet.

**Comment by nstamm** [comment]
It's aliveee @lverissimo!

**Comment by lverissimo** [comment]
Thank you!

**Comment by kauankas** [comment]
aonde que edito esse script, tem um tutorial de onde ancha o arquivo, o que fazer, etc?

**Comment by nstamm** [comment]
> aonde que edito esse script, tem um tutorial de onde ancha o arquivo, o que fazer, etc?

/usr/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/extension.js
