### ISSUE TITLE
Unable to deselect webcam

### ISSUE THREAD

**Issue by pjokinen** [EasyScreenCast/EasyScreenCast#244]
## Expected Behavior
Deselecting webcam should work.
## Current Behavior
After selecting webcam for recording, deselecting it by selecting "No WebCam recording" doesn't work, selection stays at webcam.

## Possible Solution
It seems that the "No WebCam recording" option should be value 0 but it is incremented to 1 when selected in selector. Patch below avoids incrementing the iDevice value for "No webcam" case and fixes the selector for me.

```
diff --git a/extension.js b/extension.js
index f6d4011..3b81a15 100644
--- a/extension.js
+++ b/extension.js
@@ -403,7 +403,7 @@ const EasyScreenCast_Indicator = new Lang.Class({
                 // device, we will always open it with v4l2src.
                 const device = devices[i - 1];
                 const devicePath = device.get_properties().get_string('device.path');
-                iDevice = Number(devicePath.replace(/[^0-9]+/ig, ''));
+                iDevice = Number(devicePath.replace(/[^0-9]+/ig, '')) + 1;
             }
 
             this.AreaMenuItem[i] =
@@ -419,7 +419,7 @@ const EasyScreenCast_Indicator = new Lang.Class({
                     this.connect('activate',
                         () => {
                             Lib.TalkativeLog('-*-set webcam device to ' + i + ' ' + arr[i]);
-                            Settings.setOption(Settings.DEVICE_WEBCAM_SETTING_KEY, iDevice + 1);
+                            Settings.setOption(Settings.DEVICE_WEBCAM_SETTING_KEY, iDevice);
 
                             item.label.text = arr[i];
                         });
```

## Your Environment
Fedora 31 and EasyScreenCast master

**Comment by Dilith006** [comment]
Is this solved?

**Comment by djvirus9** [comment]
I'm having the same issue. once i mitigated it with the help of google. whenever my system gets updated it gives me the same error and this time noting is helping me. kindly give a solution

**Comment by bartoszek** [comment]
Not working with `gnome-shell:3.36` :unamused:
