### ISSUE TITLE
Can't select no webcam recording

### ISSUE THREAD

**Issue by snifhex** [EasyScreenCast/EasyScreenCast#255]
Can't record without webcam and I don't want to record my webcam and I can't select no webcam recording option, it automatically reverts back to my default laptop webcam.

## Expected Behavior
After changing to "No WebCam recording" EasyScreencCast shoutd reflect the preferences and should not record webcam. 

## Current Behavior
It currently records my webcam no matter what.

## Steps to Reproduce (for bugs)

1. Select webcam once.
2. Now, can't select "No WebCam recording"
3. All Screen cast will have now a webcam window at the bottom of the screen.
4.

## Logs

 * Use `journalctl /usr/bin/gnome-shell -f` to monitor Gnome shell activity. Maybe the crash will log something.
 * Log, **enable verbose debug logs** into options window, and after that try  
 `journalctl --since=today --no-pager | grep js`
 * webcam info:
 `v4l2-ctl --all`
 * webcam info:
 `for VIDEO_DEVICE in /dev/video* ; do echo ; echo ; echo $VIDEO_DEVICE ; echo ; v4l2-ctl --device=$VIDEO_DEVICE --list-inputs ; done`
 * webcam info:
 `GST_DEBUG=v4l2src:5 gst-launch-1.0 v4l2src num-buffers=1 ! fakesink | grep probed`

## Your Environment

* Where did you download the extension?
 [ ] Gnome shell extension website
 [ ] From Git (Add commit tag)
* Gnome shell version:

* Operating System and version:
Linux 192.168.1.6 5.5.0-kali2-amd64 #1 SMP Debian 5.5.17-1kali1 (2020-04-21) x86_64 GNU/Linux

* Display server: Wayland / X11 / Other

**Comment by blipk** [comment]
Same issue here.

**Comment by timm2k** [comment]
Workaround:
`dconf write /org/gnome/shell/extensions/EasyScreenCast/device-webcam 0`

You can check state of `decive-webcam` with 
`dconf read /org/gnome/shell/extensions/EasyScreenCast/device-webcam`

Seems its a simple index of with device in list of webcams is used.

Kind regards
Timm
