### ISSUE TITLE
Error: Expected type utf8 for Argument 'accelerator' but got type 'undefined'

### ISSUE THREAD

**Issue by ilkm** [EasyScreenCast/EasyScreenCast#273]
Error: Expected type utf8 for Argument 'accelerator' but got type 'undefined'

Stack trace:
  EasyScreenCastSettingsWidget<._updateRowShortcut@/home/zi/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/prefs.js:1027:30
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  EasyScreenCastSettingsWidget<._init@/home/zi/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/prefs.js:111:13
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  buildPrefsWidget@/home/zi/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/prefs.js:1190:18
  _selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:91:22
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:243:17
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  main@resource:///org/gnome/shell/extensionPrefs/main.js:397:5
  @<main>:1:43

**Comment by adangel** [comment]
That's a duplicate of #130
