### ISSUE TITLE
Can't deselect webcam recording

### ISSUE THREAD

**Issue by Samuel20354** [EasyScreenCast/EasyScreenCast#282]
So i wanted to use my webcam for bit in my recordings but when i click the extension and click "No WebCam Recording" it doesn't change to no webcam it stays on my webcam

I have tried recording to see if it was a print error or something but my webcam was still on 
and yes i have tried reinstalling

Plz help
Thanks

**Comment by eyeskills** [comment]
This has been addressed in #255
