### ISSUE TITLE
No JS module 'screencast' found in search path

### ISSUE THREAD

**Issue by thehassantahir** [EasyScreenCast/EasyScreenCast#286]
I installed the extension from gnome extension site and now it is displaying an error "No JS module 'screencast' found in search path". My Gnome shell version is 3.38.4. Have a look on screenshot.
![screenshot](https://user-images.githubusercontent.com/54933420/121801824-cfc34e80-cc52-11eb-9663-9c453762be25.png)

As i am trying to install from repo and entering make install having an other error.
![screen-2](https://user-images.githubusercontent.com/54933420/121801821-cdf98b00-cc52-11eb-8bbd-62a3511b15db.png)

Technical details:

The settings of extension EasyScreenCast@iacopodeenosee.gmail.com had an error:
```
ReferenceError: global is not defined
```

Stack trace:
```
TalkativeLog@/home/fsociety/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/convenience.js:116:9
buildPrefsWidget@/home/fsociety/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/prefs.js:1188:9
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:207:40
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:22
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:222:19
start@resource:///org/gnome/gjs/modules/script/package.js:206:8
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

**Comment by adangel** [comment]
I think, this one is fixed with 1.3.0 (was a gnome 3.38 incompatibility issue)
