### ISSUE TITLE
Key bindings always enabled. Not able to change.

### ISSUE THREAD

**Issue by tadsn3w** [EasyScreenCast/EasyScreenCast#311]
## Expected Behavior
Tried to change <Ctl> E key binding.  It conflicts with other software.
I expect to be able to enable/disable shortcut or change the value.

## Current Behavior
The menu option has an "Active Shortcut" and when I click on the value "Invalid", changes to "New accelerator..."
It does not matter what key(s) I entered; it always return "Invalid".
The toggle button "Enable keyboard shortcut" does not have any effect.  
<Ctl> E is always enabled.

## Possible Solution
N/A

## Steps to Reproduce (for bugs)

1. Computer is active and running
2. Open any software i.e. Obsidian.  When Obsidian is running press <Ctl>E to toggle Edit/View
3. You see a crosshair to select an area.  (That is the clue EasyScreenCast is active).
4. Press <Esc> to disable it.
5. Open menu options of EasyScreenCast.
6. Toggle off the Enable keyboard shortcut.
7. Try again Obsidian <Ctl> E.  The same crosshair appears.  EasyScreeCast keybinding took over.
8. Go to the menu options of EasyScreenCast.
9. Try to change the active shortcut. Press enter on the value "Invalid"
10. Enter any other keybinding. i.e. <Ctl><Alt> E
11. It returns value "Invalid"

## Logs
```
ESC]-#-mixer stream remove - ID: 18
[ESC]-#-mixer stream remove - ID: 18
[ESC]-#-mixer stream add - ID: 20
[ESC]-#-mixer stream add - ID: 20
BingWallpaper extension: Replace icon set to : bing-symbolic
BingWallpaper extension: selected image changed to :current
BingWallpaper extension: Storing state as JSON: {"maxlongdate":202202200800,"title":"Humpback whales and dolphins, Hawaii","explanation":"Bing Wallpaper of the Day for 2022-02-20","copyright":"© drewsulockcreations/Getty Images","longstartdate":"202202200800","imageinfolink":"https://www.bing.com/search?q=humpback+baleen+whale&form=hpcapt&filters=HpDate%3a%2220220220_0800%22","imageURL":"https://www.bing.com/th?id=OHR.WhalesDolphins_EN-US8179813228_UHD.jpg","filename":"/home/tads/Pictures/BingWallpaper/20220220-WhalesDolphins_EN-US8179813228_UHD.jpg"}BingWallpaper extension: restoring state...
BingWallpaper extension: bad state - refreshing...
BingWallpaper extension: next check in 60 seconds @ local time 2022-02-20 16:43 -0800
enabling Hue Lights version 19
loading default theme (Adwaita)
[ESC]-*-enableExtension called
[ESC]-*-create indicator
[ESC]-#-mixer _init
[ESC]-#-mixer exist -> [object instance wrapper GIName:Gvc.MixerControl jsobj@0xd16f310e080 native@0x55e25fef2310] state -> 1
[ESC]-@-init webcam
[ESC]-@-gstreamer version: 1.20.0.0
[ESC]-@-plugin list: 0
[ESC]-@-device monitor created
[ESC]-@-dbus created
[ESC]-@-start video devicemonitor
[ESC]-@-refresh all video input
[ESC]-@-get devices
[ESC]-@-devices number: 0
[ESC]-°-init notify manager[ESC]-¶-init scope:[0x55e263c2ce20 Gjs_EasyScreenCast_indicator.panel-button][ESC]-#-check GVC lib presence: true
[ESC]-&-init recorder
[ESC]-*-reset the sub menu audio
[ESC]-*-add new items to sub menu audio
[ESC]-#-get list input audio
[ESC]-#-Mixer sink -> 2
[ESC]-#-sink index: 92
[ESC]-#-sink name: alsa_output.pci-0000_0a_00.1.hdmi-stereo-extra2
[ESC]-#-sink description: Ellesmere HDMI Audio [Radeon RX 470/480 / 570/580/590] Digital Stereo (HDMI 3)
[ESC]-#-sink port: hdmi-output-2
[ESC]-#-sink index: 41
[ESC]-#-sink name: alsa_output.pci-0000_0c_00.4.iec958-stereo
[ESC]-#-sink description: Starship/Matisse HD Audio Controller Digital Stereo (IEC958)
[ESC]-#-sink port: iec958-stereo-output
[ESC]-#-Mixer sources -> 0
[ESC]-#-MIXER SOURCE TOT -> 2
[ESC]-*-get audio choice from pref 0
[ESC]-@-start video devicemonitor
[ESC]-£-update draw capture[ESC]-£-update draw capture[ESC]-£-update draw capture[ESC]-£-update draw capture[ESC]-£-update draw capture[ESC]-£-update draw capture[ESC]-£-update draw captureFailed to query filesystem: method Gio.File.query_filesystem_info_async: At least 4 arguments required, but only 3 passed
Window manager warning: Trying to remove non-existent keybinding "sync-selection".
[ESC]-&-d-bus proxy connected
libinput error: event8  - Kinesis Advantage2 Keyboard: client bug: event processing lagging behind by 24ms, your system is too slow
libinput error: event8  - Kinesis Advantage2 Keyboard: client bug: event processing lagging behind by 15ms, your system is too slow

```

## Your Environment
![image](https://user-images.githubusercontent.com/44947400/154872766-503b35b7-b1fd-424f-9e4c-2d65b3dc4015.png)
* Fedora 35 WorkStation.
* OS type 64 bit
* GNOME 41.3
* Window System Wayland
* kernel-5.16.9-200.fc35.x86_64

**Comment by adangel** [comment]
Currently, the keybinding is only activated/deactived when the extension is started. The tooltip says this: 
![grafik](https://user-images.githubusercontent.com/1573684/156782257-6662bf39-8de8-42e9-969f-7dbce9c893c9.png)

But restarting the extension means - logging off and in again (e.g. restart the whole gnome session). That is not great. But it can be actually done without restarting. See #318 .

**Comment by adangel** [comment]
Note - you might also run into #130 - which is only fixed on the master branch.
