### ISSUE TITLE
TypeError: this._settings.destory is not a function

### ISSUE THREAD

**Issue by reupen** [EasyScreenCast/EasyScreenCast#330]
I updated the extension this morning, and after logging out and in there was still an extension error being reported.

## Expected Behavior

Extension should load (or incompatible versions should not be offered).

## Current Behavior

An error is reported.

## Possible Solution

It looks like there's a typo on this line:

https://github.com/EasyScreenCast/EasyScreenCast/blob/38397915ef3cb97a66ee57d51924c614713e01ce/extension.js#L973

(destory instead of destroy.)

I manually fixed the typo locally and the extension loaded after logging out and in again (it looks like recording doesn't work, but that's a separate problem).

## Steps to Reproduce (for bugs)

1. Install extension from https://extensions.gnome.org/ on Ubuntu 21.10
2. Check logs for error

## Logs

```
JS ERROR: Extension EasyScreenCast@iacopodeenosee.gmail.com: TypeError: this._settings.destory is not a function
destroy@/home/reupen/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/extension.js:973:28
disable@/home/reupen/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/extension.js:1022:19
_callExtensionDisable@resource:///org/gnome/shell/ui/extensionSystem.js:109:32
_disableAllExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:622:22
_disableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:621:52
_sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:639:18
_emit@resource:///org/gnome/gjs/modules/core/_signals.js:114:47
_sync@resource:///org/gnome/shell/ui/sessionMode.js:200:14
pushMode@resource:///org/gnome/shell/ui/sessionMode.js:161:14
activate@resource:///org/gnome/shell/ui/screenShield.js:646:34
_onLongLightbox@resource:///org/gnome/shell/ui/screenShield.js:372:18
onComplete@resource:///org/gnome/shell/ui/lightbox.js:193:18
_makeEaseCallback/<@resource:///org/gnome/shell/ui/environment.js:85:13
_easeActor/<@resource:///org/gnome/shell/ui/environment.js:168:64
```

## Your Environment

* Where did you download the extension?

- [x] Gnome shell extension website
- [ ] From Git (Add commit tag)

* Gnome shell version:

40.5

* Operating System and version:

Ubuntu 21.10

* Display server: Wayland / X11 / Other

Wayland

**Comment by adangel** [comment]
Thanks for reporting.
Yes, that's a typo. The extension is disabled e.g. when you lock your screen. If you logout and login again, the extension is initialized fresh and works again - until you lock again.

I'll fix it soon.
