### ISSUE TITLE
File path is incorrect

### ISSUE THREAD

**Issue by JesseMaurais** [EasyScreenCast/EasyScreenCast#336]
File path used to write video to disk is incorrect.

## Expected Behavior
File is written to disk in the selected directory, following the given pattern for the base file name..

## Current Behavior
If the file name template was specified with date or time, no file is generated *at all*

If I specified a file name as something like "dumb_name" and I selected as my destination folder something like "/mnt/User/jesse" then a file is generated in my XDG videos directory with the name "_mnt_User_jesse_dumb_name.mp4" 

## Possible Solution
The calculation of the file path given the name template and the destination directory likely has two possibly unrelated issues. The first is that the template is not filling out the date and time tags, which is why it only works if I do not specify them. I suspect that the file fails to be created because the "%" characters remaining in the string after the substitution failure are not valid in a file name. Even so, no error of this kind is indicated. It just fails to write. 

The second issue has to do with the directory. I have my XDG directories set to a path outside of my home folder on another partition. I'm not sure if this matters but it is specified in the "user-dirs.dirs" file. The strange thing is that the selected directory becomes part of the base file name and that this is written into my XDG videos directory regardless of what I had selected as the destination. In the past I have had problems with using non-default user dirs but never anything like this.

## Steps to Reproduce (for bugs)
1. Set the XDG videos directory away from the home folder (in user-dirs.dirs)
2. Use "dumb_name" as the file name template
3. Choose some other directory for the file
4. Start recording

## Logs
The most relevant part seems to be this line
[ESC]-*-update abs file path -> /mnt/User/jesse/Videos/_mnt_User_jesse_dumb_name.mp4
But here's all of the gnome shell log

Ignoring length property that isn't a number at line 2731, col 24
Ignoring length property that isn't a number at line 2741, col 24
libinput error: event2  - Compx 2.4G Wireless Receiver: client bug: event processing lagging behind by 38ms, your system is too slow
libinput error: event8  - Logitech USB Receiver: client bug: event processing lagging behind by 62ms, your system is too slow
Ignoring length property that isn't a number at line 2731, col 24
Ignoring length property that isn't a number at line 2741, col 24
libinput error: client bug: timer event8 debounce short: scheduled expiry is in the past (-5ms), your system is too slow
Ignoring length property that isn't a number at line 2731, col 24
Ignoring length property that isn't a number at line 2741, col 24
Ignoring length property that isn't a number at line 2731, col 24
Ignoring length property that isn't a number at line 2741, col 24
Couldn't find child [0x56136fb68070 Gjs_ui_windowPreview_WindowPreview ("jesse@debian: ~")] in window slots
Couldn't find child [0x561376992570 Gjs_ui_windowPreview_WindowPreview ("Software")] in window slots
Couldn't find child [0x56137038be70 Gjs_ui_windowPreview_WindowPreview ("easyscreencast does not save file - Google Search — Mozilla Firefox")] in window slotIgnoring length property that isn't a number at line 2731, col 24
Ignoring length property that isn't a number at line 2741, col 24
Couldn't find child [0x56136fb68070 Gjs_ui_windowPreview_WindowPreview:first-child ("jesse@debian: ~")] in window slots
Couldn't find child [0x561376992570 Gjs_ui_windowPreview_WindowPreview ("Software")] in window slots
Couldn't find child [0x56137038be70 Gjs_ui_windowPreview_WindowPreview:last-child ("easyscreencast does not save file - Google Search — Mozilla Firefox")] in window slot[ESC]-*-refresh indicator -A false -F true
[ESC]-*-refresh indicator -A false -F false
[ESC]-*-refresh indicator -A false -F true
Ignoring length property that isn't a number at line 2731, col 24
Ignoring length property that isn't a number at line 2741, col 24
[ESC]-*-left click indicator
[ESC]-*-reset the sub menu audio
[ESC]-*-add new items to sub menu audio
[ESC]-#-get list input audio
[ESC]-#-Mixer sink -> 4
[ESC]-#-sink index: 0
[ESC]-#-sink name: alsa_output.pci-0000_24_00.0.analog-stereo
[ESC]-#-sink description: Sound Core3D [Sound Blaster Recon3D / Z-Series] (SB1570 SB Audigy Fx) Analog Stereo
[ESC]-#-sink port: analog-output-lineout
[ESC]-#-sink index: 5
[ESC]-#-sink name: alsa_output.pci-0000_29_00.1.hdmi-stereo
[ESC]-#-sink description: Navi 10 HDMI Audio Digital Stereo (HDMI)
[ESC]-#-sink port: hdmi-output-0
[ESC]-#-sink index: 2
[ESC]-#-sink name: alsa_output.pci-0000_2c_00.3.iec958-stereo
[ESC]-#-sink description: Family 17h (Models 00h-0fh) HD Audio Controller Digital Stereo (IEC958)
[ESC]-#-sink port: iec958-stereo-output
[ESC]-#-sink index: 3
[ESC]-#-sink name: bluez_sink.74_EC_B2_B6_09_3A.a2dp_sink
[ESC]-#-sink description: Echo Dot-983
[ESC]-#-sink port: speaker-output
[ESC]-#-Mixer sources -> 1
[ESC]-#-source index: 1
[ESC]-#-source name: alsa_input.pci-0000_24_00.0.analog-stereo
[ESC]-#-source description: Sound Core3D [Sound Blaster Recon3D / Z-Series] (SB1570 SB Audigy Fx) Analog Stereo
[ESC]-#-source port: analog-input-linein
[ESC]-#-MIXER SOURCE TOT -> 5
[ESC]-*-get audio choice from pref 0
[ESC]-@-get devices
[ESC]-@-devices number: 0
[ESC]-@-devices number after filtering for v4l2: 0
[ESC]-@-get name devices
[ESC]-@-list devices name: 
[ESC]-*-webcam list: No WebCam recording
[ESC]-*-webcam i=0 menu-item-text: No WebCam recording
[ESC]-*-populated submenuwebcam. Settings i=0
[ESC]-@-start video devicemonitor
[ESC]-*-refresh indicator -A false -F false
[ESC]-*-refresh indicator -A false -F true
[ESC]-*-left click indicator
[ESC]-*-reset the sub menu audio
[ESC]-*-add new items to sub menu audio
[ESC]-#-get list input audio
[ESC]-#-Mixer sink -> 4
[ESC]-#-sink index: 0
[ESC]-#-sink name: alsa_output.pci-0000_24_00.0.analog-stereo
[ESC]-#-sink description: Sound Core3D [Sound Blaster Recon3D / Z-Series] (SB1570 SB Audigy Fx) Analog Stereo
[ESC]-#-sink port: analog-output-lineout
[ESC]-#-sink index: 5
[ESC]-#-sink name: alsa_output.pci-0000_29_00.1.hdmi-stereo
[ESC]-#-sink description: Navi 10 HDMI Audio Digital Stereo (HDMI)
[ESC]-#-sink port: hdmi-output-0
[ESC]-#-sink index: 2
[ESC]-#-sink name: alsa_output.pci-0000_2c_00.3.iec958-stereo
[ESC]-#-sink description: Family 17h (Models 00h-0fh) HD Audio Controller Digital Stereo (IEC958)
[ESC]-#-sink port: iec958-stereo-output
[ESC]-#-sink index: 3
[ESC]-#-sink name: bluez_sink.74_EC_B2_B6_09_3A.a2dp_sink
[ESC]-#-sink description: Echo Dot-983
[ESC]-#-sink port: speaker-output
[ESC]-#-Mixer sources -> 1
[ESC]-#-source index: 1
[ESC]-#-source name: alsa_input.pci-0000_24_00.0.analog-stereo
[ESC]-#-source description: Sound Core3D [Sound Blaster Recon3D / Z-Series] (SB1570 SB Audigy Fx) Analog Stereo
[ESC]-#-source port: analog-input-linein
[ESC]-#-MIXER SOURCE TOT -> 5
[ESC]-*-get audio choice from pref 0
[ESC]-@-get devices
[ESC]-@-devices number: 0
[ESC]-@-devices number after filtering for v4l2: 0
[ESC]-@-get name devices
[ESC]-@-list devices name: 
[ESC]-*-webcam list: No WebCam recording
[ESC]-*-webcam i=0 menu-item-text: No WebCam recording
[ESC]-*-populated submenuwebcam. Settings i=0
[ESC]-@-start video devicemonitor
[ESC]-*-refresh indicator -A false -F false
libinput error: event8  - Logitech USB Receiver: client bug: event processing lagging behind by 11ms, your system is too slow
[ESC]-*-start recording
[ESC]-*-recording full area
[ESC]-*-instant recording called
[ESC]-&-start video recording
[ESC]-§-get file extension C-> 2[ESC]-§-COMPOSE GSP[ESC]-§-get option||devW: ||devA: 0||Qgsp: 1||Qwc: ||Res: -1||Cont: 2[ESC]-§-SCREEN[ESC]-§-resolution option: -1[ESC]-§-compose resolution: [ESC]-§-final GSP : x264enc psy-tune="animation" speed-preset="fast" subme=5 qp-min=18 qp-max=28 threads=%T ! queue max-size-buffers=0 max-size-time=0 max-size-bytes=0 ! mp4mux[ESC]-&-path/file template : /mnt/User/jesse/dumb_name.mp4
[ESC]-&-path/file final : _mnt_User_jesse_dumb_name.mp4
[ESC]-*-refresh indicator -A false -F false
[ESC]-&-screencast execute - true - /mnt/User/jesse/Videos/_mnt_User_jesse_dumb_name.mp4
[ESC]-*-record OK
[ESC]-*-show notify
[ESC]-°-create notify :Start Recording[ESC]-%-init TimerCounting called
[ESC]-%-setcallback TimerCounting called
[ESC]-%-start TimerCounting called
[ESC]-*-update abs file path -> /mnt/User/jesse/Videos/_mnt_User_jesse_dumb_name.mp4
[ESC]-*-refresh indicator -A true -F false
libinput error: event8  - Logitech USB Receiver: client bug: event processing lagging behind by 22ms, your system is too slow
[ESC]-%-continued TimerCounting | sec: 1
[ESC]-°-update notify[ESC]-%-continued TimerCounting | sec: 2
[ESC]-°-update notify[ESC]-%-continued TimerCounting | sec: 3
[ESC]-°-update notify[ESC]-%-continued TimerCounting | sec: 4
[ESC]-°-update notify[ESC]-%-continued TimerCounting | sec: 5
[ESC]-°-update notify[ESC]-*-refresh indicator -A true -F true
[ESC]-*-left click indicator
[ESC]-*-reset the sub menu audio
[ESC]-*-add new items to sub menu audio
[ESC]-#-get list input audio
[ESC]-#-Mixer sink -> 4
[ESC]-#-sink index: 0
[ESC]-#-sink name: alsa_output.pci-0000_24_00.0.analog-stereo
[ESC]-#-sink description: Sound Core3D [Sound Blaster Recon3D / Z-Series] (SB1570 SB Audigy Fx) Analog Stereo
[ESC]-#-sink port: analog-output-lineout
[ESC]-#-sink index: 5
[ESC]-#-sink name: alsa_output.pci-0000_29_00.1.hdmi-stereo
[ESC]-#-sink description: Navi 10 HDMI Audio Digital Stereo (HDMI)
[ESC]-#-sink port: hdmi-output-0
[ESC]-#-sink index: 2
[ESC]-#-sink name: alsa_output.pci-0000_2c_00.3.iec958-stereo
[ESC]-#-sink description: Family 17h (Models 00h-0fh) HD Audio Controller Digital Stereo (IEC958)
[ESC]-#-sink port: iec958-stereo-output
[ESC]-#-sink index: 3
[ESC]-#-sink name: bluez_sink.74_EC_B2_B6_09_3A.a2dp_sink
[ESC]-#-sink description: Echo Dot-983
[ESC]-#-sink port: speaker-output
[ESC]-#-Mixer sources -> 1
[ESC]-#-source index: 1
[ESC]-#-source name: alsa_input.pci-0000_24_00.0.analog-stereo
[ESC]-#-source description: Sound Core3D [Sound Blaster Recon3D / Z-Series] (SB1570 SB Audigy Fx) Analog Stereo
[ESC]-#-source port: analog-input-linein
[ESC]-#-MIXER SOURCE TOT -> 5
[ESC]-*-get audio choice from pref 0
[ESC]-@-get devices
[ESC]-@-devices number: 0
[ESC]-@-devices number after filtering for v4l2: 0
[ESC]-@-get name devices
[ESC]-@-list devices name: 
[ESC]-*-webcam list: No WebCam recording
[ESC]-*-webcam i=0 menu-item-text: No WebCam recording
[ESC]-*-populated submenuwebcam. Settings i=0
[ESC]-@-start video devicemonitor
[ESC]-%-continued TimerCounting | sec: 6
[ESC]-°-update notify[ESC]-*-refresh indicator -A true -F false
[ESC]-*-stop recording
[ESC]-&-stop video recording
[ESC]-*-refresh indicator -A false -F false
[ESC]-%-finish TimerCounting 
[ESC]-°-update notify[ESC]-%-stop TimerCounting called
[ESC]-&-screencast stop - true

## Environment
* Installed from gnome extensions website
* Gnome shell version 3.38.5
* Operating System and version: Debian 11 (bullseye) with Linux kernel 5.10.0
* Display server: Wayland

**Comment by adangel** [comment]
The critical code line seems to be this one:

https://github.com/EasyScreenCast/EasyScreenCast/blob/075ee4771563931646857c169cbdb48fc6e69c62/utilrecorder.js#L194

If a specific folder is selected, then `template` doesn't only contain the filename, but the complete path.

Refs #306, #188
