### ISSUE TITLE
Chinese translation

### ISSUE THREAD

**Issue by d2school** [EasyScreenCast/EasyScreenCast#350]
PoEdit can't open the:  [easyscreencast.pot](https://github.com/EasyScreenCast/EasyScreenCast/blob/master/locale/easyscreencast.pot) on master. 

I made the Chinese translation  base on tag 1.7.1 .

file zh.po: 
[zh.zip](https://github.com/EasyScreenCast/EasyScreenCast/files/12207142/zh.zip)

**Comment by adangel** [comment]
Thanks!
