### ISSUE TITLE
Show recording time alongside the extension icon instead showing a notification

### ISSUE THREAD

**Issue by jjnilton** [EasyScreenCast/EasyScreenCast#84]
Could be possible to show recording time alongside the extension icon instead a notification? In the current way, the notification disappears after 5 seconds and then there's no way to keep tracking the recording time.

Something like this: 
![recording-indicator](https://cloud.githubusercontent.com/assets/228200/15510118/89c33540-21ac-11e6-8ae9-37017b80ccda.png)

Some way to pin the notification while recording could work too.

**Comment by tobias47n9e** [comment]
@jjnilton I made a first implementation of this in #117. Do you think it needs any options? Maybe some users want to turn it off?

**Comment by jjnilton** [comment]
@tobias47n9e thanks! I think that an option to disable would be good for those that doesn't want it.

My suggestion to pin notification was just an alternative in case it wasn't possible to implement the recording time in the top bar, or if the suggestion wasn't accepted. I think the information on the top bar is enough.
